export const ROLE_MAP = {
  USER_ROLE_UNSPECIFIED: 'Разработчик',
  USER_ROLE_DEVELOPER: 'Разработчик',
  USER_ROLE_MODERATOR: 'Модератор',
  USER_ROLE_ADMIN: 'Администратор',
};

export const USER_ROLES = {
  UNSPECIFIED: 'USER_ROLE_UNSPECIFIED',
  DEVELOPER: 'USER_ROLE_DEVELOPER',
  MODERATOR: 'USER_ROLE_MODERATOR',
  ADMIN: 'USER_ROLE_ADMIN',
};
