version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - contextcheck
    - durationcheck
    - errcheck
    - errorlint
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - revive
    - sqlclosecheck
    - staticcheck
    - unparam
    - unused
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        source: '^//go:generate '
      - linters:
          - revive
        path: _test\.go
        text: seems to be unused, consider removing or renaming it as _
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
