// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: moderation/v1/moderation.proto

package moderationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModerationService_SubmitDraft_FullMethodName               = "/moderation.v1.ModerationService/SubmitDraft"
	ModerationService_ListRequests_FullMethodName              = "/moderation.v1.ModerationService/ListRequests"
	ModerationService_GetRequest_FullMethodName                = "/moderation.v1.ModerationService/GetRequest"
	ModerationService_GetLatestRequestByProject_FullMethodName = "/moderation.v1.ModerationService/GetLatestRequestByProject"
	ModerationService_ClaimRequest_FullMethodName              = "/moderation.v1.ModerationService/ClaimRequest"
	ModerationService_Approve_FullMethodName                   = "/moderation.v1.ModerationService/Approve"
	ModerationService_Reject_FullMethodName                    = "/moderation.v1.ModerationService/Reject"
	ModerationService_SendMessage_FullMethodName               = "/moderation.v1.ModerationService/SendMessage"
	ModerationService_ListMessages_FullMethodName              = "/moderation.v1.ModerationService/ListMessages"
	ModerationService_ListActiveChats_FullMethodName           = "/moderation.v1.ModerationService/ListActiveChats"
	ModerationService_CloseDialog_FullMethodName               = "/moderation.v1.ModerationService/CloseDialog"
)

// ModerationServiceClient is the client API for ModerationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModerationServiceClient interface {
	SubmitDraft(ctx context.Context, in *SubmitDraftRequest, opts ...grpc.CallOption) (*SubmitDraftResponse, error)
	ListRequests(ctx context.Context, in *ListModerationRequestsRequest, opts ...grpc.CallOption) (*ListModerationRequestsResponse, error)
	GetRequest(ctx context.Context, in *GetModerationRequestRequest, opts ...grpc.CallOption) (*GetModerationRequestResponse, error)
	GetLatestRequestByProject(ctx context.Context, in *GetLatestRequestByProjectRequest, opts ...grpc.CallOption) (*GetModerationRequestResponse, error)
	ClaimRequest(ctx context.Context, in *ClaimModerationRequestRequest, opts ...grpc.CallOption) (*ClaimModerationRequestResponse, error)
	Approve(ctx context.Context, in *ApproveModerationRequest, opts ...grpc.CallOption) (*ApproveModerationResponse, error)
	Reject(ctx context.Context, in *RejectModerationRequest, opts ...grpc.CallOption) (*RejectModerationResponse, error)
	SendMessage(ctx context.Context, in *SendChatMessageRequest, opts ...grpc.CallOption) (*SendChatMessageResponse, error)
	ListMessages(ctx context.Context, in *ListChatMessagesRequest, opts ...grpc.CallOption) (*ListChatMessagesResponse, error)
	ListActiveChats(ctx context.Context, in *ListActiveChatsRequest, opts ...grpc.CallOption) (*ListActiveChatsResponse, error)
	CloseDialog(ctx context.Context, in *CloseDialogRequest, opts ...grpc.CallOption) (*CloseDialogResponse, error)
}

type moderationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModerationServiceClient(cc grpc.ClientConnInterface) ModerationServiceClient {
	return &moderationServiceClient{cc}
}

func (c *moderationServiceClient) SubmitDraft(ctx context.Context, in *SubmitDraftRequest, opts ...grpc.CallOption) (*SubmitDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitDraftResponse)
	err := c.cc.Invoke(ctx, ModerationService_SubmitDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) ListRequests(ctx context.Context, in *ListModerationRequestsRequest, opts ...grpc.CallOption) (*ListModerationRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModerationRequestsResponse)
	err := c.cc.Invoke(ctx, ModerationService_ListRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) GetRequest(ctx context.Context, in *GetModerationRequestRequest, opts ...grpc.CallOption) (*GetModerationRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModerationRequestResponse)
	err := c.cc.Invoke(ctx, ModerationService_GetRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) GetLatestRequestByProject(ctx context.Context, in *GetLatestRequestByProjectRequest, opts ...grpc.CallOption) (*GetModerationRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModerationRequestResponse)
	err := c.cc.Invoke(ctx, ModerationService_GetLatestRequestByProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) ClaimRequest(ctx context.Context, in *ClaimModerationRequestRequest, opts ...grpc.CallOption) (*ClaimModerationRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimModerationRequestResponse)
	err := c.cc.Invoke(ctx, ModerationService_ClaimRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) Approve(ctx context.Context, in *ApproveModerationRequest, opts ...grpc.CallOption) (*ApproveModerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveModerationResponse)
	err := c.cc.Invoke(ctx, ModerationService_Approve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) Reject(ctx context.Context, in *RejectModerationRequest, opts ...grpc.CallOption) (*RejectModerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectModerationResponse)
	err := c.cc.Invoke(ctx, ModerationService_Reject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) SendMessage(ctx context.Context, in *SendChatMessageRequest, opts ...grpc.CallOption) (*SendChatMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendChatMessageResponse)
	err := c.cc.Invoke(ctx, ModerationService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) ListMessages(ctx context.Context, in *ListChatMessagesRequest, opts ...grpc.CallOption) (*ListChatMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChatMessagesResponse)
	err := c.cc.Invoke(ctx, ModerationService_ListMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) ListActiveChats(ctx context.Context, in *ListActiveChatsRequest, opts ...grpc.CallOption) (*ListActiveChatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActiveChatsResponse)
	err := c.cc.Invoke(ctx, ModerationService_ListActiveChats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) CloseDialog(ctx context.Context, in *CloseDialogRequest, opts ...grpc.CallOption) (*CloseDialogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseDialogResponse)
	err := c.cc.Invoke(ctx, ModerationService_CloseDialog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModerationServiceServer is the server API for ModerationService service.
// All implementations must embed UnimplementedModerationServiceServer
// for forward compatibility.
type ModerationServiceServer interface {
	SubmitDraft(context.Context, *SubmitDraftRequest) (*SubmitDraftResponse, error)
	ListRequests(context.Context, *ListModerationRequestsRequest) (*ListModerationRequestsResponse, error)
	GetRequest(context.Context, *GetModerationRequestRequest) (*GetModerationRequestResponse, error)
	GetLatestRequestByProject(context.Context, *GetLatestRequestByProjectRequest) (*GetModerationRequestResponse, error)
	ClaimRequest(context.Context, *ClaimModerationRequestRequest) (*ClaimModerationRequestResponse, error)
	Approve(context.Context, *ApproveModerationRequest) (*ApproveModerationResponse, error)
	Reject(context.Context, *RejectModerationRequest) (*RejectModerationResponse, error)
	SendMessage(context.Context, *SendChatMessageRequest) (*SendChatMessageResponse, error)
	ListMessages(context.Context, *ListChatMessagesRequest) (*ListChatMessagesResponse, error)
	ListActiveChats(context.Context, *ListActiveChatsRequest) (*ListActiveChatsResponse, error)
	CloseDialog(context.Context, *CloseDialogRequest) (*CloseDialogResponse, error)
	mustEmbedUnimplementedModerationServiceServer()
}

// UnimplementedModerationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModerationServiceServer struct{}

func (UnimplementedModerationServiceServer) SubmitDraft(context.Context, *SubmitDraftRequest) (*SubmitDraftResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitDraft not implemented")
}
func (UnimplementedModerationServiceServer) ListRequests(context.Context, *ListModerationRequestsRequest) (*ListModerationRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRequests not implemented")
}
func (UnimplementedModerationServiceServer) GetRequest(context.Context, *GetModerationRequestRequest) (*GetModerationRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRequest not implemented")
}
func (UnimplementedModerationServiceServer) GetLatestRequestByProject(context.Context, *GetLatestRequestByProjectRequest) (*GetModerationRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestRequestByProject not implemented")
}
func (UnimplementedModerationServiceServer) ClaimRequest(context.Context, *ClaimModerationRequestRequest) (*ClaimModerationRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimRequest not implemented")
}
func (UnimplementedModerationServiceServer) Approve(context.Context, *ApproveModerationRequest) (*ApproveModerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Approve not implemented")
}
func (UnimplementedModerationServiceServer) Reject(context.Context, *RejectModerationRequest) (*RejectModerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reject not implemented")
}
func (UnimplementedModerationServiceServer) SendMessage(context.Context, *SendChatMessageRequest) (*SendChatMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedModerationServiceServer) ListMessages(context.Context, *ListChatMessagesRequest) (*ListChatMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMessages not implemented")
}
func (UnimplementedModerationServiceServer) ListActiveChats(context.Context, *ListActiveChatsRequest) (*ListActiveChatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActiveChats not implemented")
}
func (UnimplementedModerationServiceServer) CloseDialog(context.Context, *CloseDialogRequest) (*CloseDialogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseDialog not implemented")
}
func (UnimplementedModerationServiceServer) mustEmbedUnimplementedModerationServiceServer() {}
func (UnimplementedModerationServiceServer) testEmbeddedByValue()                           {}

// UnsafeModerationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModerationServiceServer will
// result in compilation errors.
type UnsafeModerationServiceServer interface {
	mustEmbedUnimplementedModerationServiceServer()
}

func RegisterModerationServiceServer(s grpc.ServiceRegistrar, srv ModerationServiceServer) {
	// If the following call panics, it indicates UnimplementedModerationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModerationService_ServiceDesc, srv)
}

func _ModerationService_SubmitDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).SubmitDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_SubmitDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).SubmitDraft(ctx, req.(*SubmitDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_ListRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModerationRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).ListRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_ListRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).ListRequests(ctx, req.(*ListModerationRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_GetRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModerationRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).GetRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_GetRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).GetRequest(ctx, req.(*GetModerationRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_GetLatestRequestByProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestRequestByProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).GetLatestRequestByProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_GetLatestRequestByProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).GetLatestRequestByProject(ctx, req.(*GetLatestRequestByProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_ClaimRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimModerationRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).ClaimRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_ClaimRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).ClaimRequest(ctx, req.(*ClaimModerationRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_Approve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveModerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).Approve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_Approve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).Approve(ctx, req.(*ApproveModerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_Reject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectModerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).Reject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_Reject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).Reject(ctx, req.(*RejectModerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendChatMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).SendMessage(ctx, req.(*SendChatMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_ListMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChatMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).ListMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_ListMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).ListMessages(ctx, req.(*ListChatMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_ListActiveChats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveChatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).ListActiveChats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_ListActiveChats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).ListActiveChats(ctx, req.(*ListActiveChatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_CloseDialog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseDialogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).CloseDialog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModerationService_CloseDialog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).CloseDialog(ctx, req.(*CloseDialogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModerationService_ServiceDesc is the grpc.ServiceDesc for ModerationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModerationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moderation.v1.ModerationService",
	HandlerType: (*ModerationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitDraft",
			Handler:    _ModerationService_SubmitDraft_Handler,
		},
		{
			MethodName: "ListRequests",
			Handler:    _ModerationService_ListRequests_Handler,
		},
		{
			MethodName: "GetRequest",
			Handler:    _ModerationService_GetRequest_Handler,
		},
		{
			MethodName: "GetLatestRequestByProject",
			Handler:    _ModerationService_GetLatestRequestByProject_Handler,
		},
		{
			MethodName: "ClaimRequest",
			Handler:    _ModerationService_ClaimRequest_Handler,
		},
		{
			MethodName: "Approve",
			Handler:    _ModerationService_Approve_Handler,
		},
		{
			MethodName: "Reject",
			Handler:    _ModerationService_Reject_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _ModerationService_SendMessage_Handler,
		},
		{
			MethodName: "ListMessages",
			Handler:    _ModerationService_ListMessages_Handler,
		},
		{
			MethodName: "ListActiveChats",
			Handler:    _ModerationService_ListActiveChats_Handler,
		},
		{
			MethodName: "CloseDialog",
			Handler:    _ModerationService_CloseDialog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moderation/v1/moderation.proto",
}
