// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: orchestrator/v1/build.proto

package orchestratorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BuildService_Upload_FullMethodName       = "/orchestrator.v1.BuildService/Upload"
	BuildService_UploadStream_FullMethodName = "/orchestrator.v1.BuildService/UploadStream"
	BuildService_List_FullMethodName         = "/orchestrator.v1.BuildService/List"
	BuildService_Get_FullMethodName          = "/orchestrator.v1.BuildService/Get"
	BuildService_Delete_FullMethodName       = "/orchestrator.v1.BuildService/Delete"
)

// BuildServiceClient is the client API for BuildService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис управления серверными билдами.
type BuildServiceClient interface {
	// Загрузить серверный билд.
	Upload(ctx context.Context, in *BuildServiceUploadRequest, opts ...grpc.CallOption) (*BuildServiceUploadResponse, error)
	// Внутренний streaming upload для gateway → orchestrator.
	// Первое сообщение содержит метаданные, последующие — чанки данных (64 КБ).
	// Не имеет HTTP binding — используется только напрямую через gRPC.
	UploadStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BuildServiceUploadStreamRequest, BuildServiceUploadResponse], error)
	// Список билдов игры.
	List(ctx context.Context, in *BuildServiceListRequest, opts ...grpc.CallOption) (*BuildServiceListResponse, error)
	// Информация о конкретном билде.
	Get(ctx context.Context, in *BuildServiceGetRequest, opts ...grpc.CallOption) (*BuildServiceGetResponse, error)
	// Удалить серверный билд.
	Delete(ctx context.Context, in *BuildServiceDeleteRequest, opts ...grpc.CallOption) (*BuildServiceDeleteResponse, error)
}

type buildServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBuildServiceClient(cc grpc.ClientConnInterface) BuildServiceClient {
	return &buildServiceClient{cc}
}

func (c *buildServiceClient) Upload(ctx context.Context, in *BuildServiceUploadRequest, opts ...grpc.CallOption) (*BuildServiceUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildServiceUploadResponse)
	err := c.cc.Invoke(ctx, BuildService_Upload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildServiceClient) UploadStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BuildServiceUploadStreamRequest, BuildServiceUploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BuildService_ServiceDesc.Streams[0], BuildService_UploadStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BuildServiceUploadStreamRequest, BuildServiceUploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BuildService_UploadStreamClient = grpc.ClientStreamingClient[BuildServiceUploadStreamRequest, BuildServiceUploadResponse]

func (c *buildServiceClient) List(ctx context.Context, in *BuildServiceListRequest, opts ...grpc.CallOption) (*BuildServiceListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildServiceListResponse)
	err := c.cc.Invoke(ctx, BuildService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildServiceClient) Get(ctx context.Context, in *BuildServiceGetRequest, opts ...grpc.CallOption) (*BuildServiceGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildServiceGetResponse)
	err := c.cc.Invoke(ctx, BuildService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildServiceClient) Delete(ctx context.Context, in *BuildServiceDeleteRequest, opts ...grpc.CallOption) (*BuildServiceDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildServiceDeleteResponse)
	err := c.cc.Invoke(ctx, BuildService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuildServiceServer is the server API for BuildService service.
// All implementations must embed UnimplementedBuildServiceServer
// for forward compatibility.
//
// Сервис управления серверными билдами.
type BuildServiceServer interface {
	// Загрузить серверный билд.
	Upload(context.Context, *BuildServiceUploadRequest) (*BuildServiceUploadResponse, error)
	// Внутренний streaming upload для gateway → orchestrator.
	// Первое сообщение содержит метаданные, последующие — чанки данных (64 КБ).
	// Не имеет HTTP binding — используется только напрямую через gRPC.
	UploadStream(grpc.ClientStreamingServer[BuildServiceUploadStreamRequest, BuildServiceUploadResponse]) error
	// Список билдов игры.
	List(context.Context, *BuildServiceListRequest) (*BuildServiceListResponse, error)
	// Информация о конкретном билде.
	Get(context.Context, *BuildServiceGetRequest) (*BuildServiceGetResponse, error)
	// Удалить серверный билд.
	Delete(context.Context, *BuildServiceDeleteRequest) (*BuildServiceDeleteResponse, error)
	mustEmbedUnimplementedBuildServiceServer()
}

// UnimplementedBuildServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBuildServiceServer struct{}

func (UnimplementedBuildServiceServer) Upload(context.Context, *BuildServiceUploadRequest) (*BuildServiceUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedBuildServiceServer) UploadStream(grpc.ClientStreamingServer[BuildServiceUploadStreamRequest, BuildServiceUploadResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadStream not implemented")
}
func (UnimplementedBuildServiceServer) List(context.Context, *BuildServiceListRequest) (*BuildServiceListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedBuildServiceServer) Get(context.Context, *BuildServiceGetRequest) (*BuildServiceGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedBuildServiceServer) Delete(context.Context, *BuildServiceDeleteRequest) (*BuildServiceDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBuildServiceServer) mustEmbedUnimplementedBuildServiceServer() {}
func (UnimplementedBuildServiceServer) testEmbeddedByValue()                      {}

// UnsafeBuildServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuildServiceServer will
// result in compilation errors.
type UnsafeBuildServiceServer interface {
	mustEmbedUnimplementedBuildServiceServer()
}

func RegisterBuildServiceServer(s grpc.ServiceRegistrar, srv BuildServiceServer) {
	// If the following call panics, it indicates UnimplementedBuildServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BuildService_ServiceDesc, srv)
}

func _BuildService_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildServiceUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildService_Upload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).Upload(ctx, req.(*BuildServiceUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildService_UploadStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BuildServiceServer).UploadStream(&grpc.GenericServerStream[BuildServiceUploadStreamRequest, BuildServiceUploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BuildService_UploadStreamServer = grpc.ClientStreamingServer[BuildServiceUploadStreamRequest, BuildServiceUploadResponse]

func _BuildService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildServiceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).List(ctx, req.(*BuildServiceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildServiceGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).Get(ctx, req.(*BuildServiceGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildServiceDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).Delete(ctx, req.(*BuildServiceDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BuildService_ServiceDesc is the grpc.ServiceDesc for BuildService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuildService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestrator.v1.BuildService",
	HandlerType: (*BuildServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upload",
			Handler:    _BuildService_Upload_Handler,
		},
		{
			MethodName: "List",
			Handler:    _BuildService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _BuildService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BuildService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadStream",
			Handler:       _BuildService_UploadStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "orchestrator/v1/build.proto",
}
