// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orchestrator/v1/build.proto

package orchestratorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadBuildRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	GameId int64                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	// Docker image tar-архив (результат `docker save`).
	ImageData     []byte   `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	BuildVersion  string   `protobuf:"bytes,3,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	Protocol      Protocol `protobuf:"varint,4,opt,name=protocol,proto3,enum=orchestrator.v1.Protocol" json:"protocol,omitempty"`
	InternalPort  uint32   `protobuf:"varint,5,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"`
	MaxPlayers    uint32   `protobuf:"varint,6,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBuildRequest) Reset() {
	*x = UploadBuildRequest{}
	mi := &file_orchestrator_v1_build_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBuildRequest) ProtoMessage() {}

func (x *UploadBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_build_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBuildRequest.ProtoReflect.Descriptor instead.
func (*UploadBuildRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_build_proto_rawDescGZIP(), []int{0}
}

func (x *UploadBuildRequest) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *UploadBuildRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *UploadBuildRequest) GetBuildVersion() string {
	if x != nil {
		return x.BuildVersion
	}
	return ""
}

func (x *UploadBuildRequest) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *UploadBuildRequest) GetInternalPort() uint32 {
	if x != nil {
		return x.InternalPort
	}
	return 0
}

func (x *UploadBuildRequest) GetMaxPlayers() uint32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

type UploadBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Build         *ServerBuild           `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBuildResponse) Reset() {
	*x = UploadBuildResponse{}
	mi := &file_orchestrator_v1_build_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBuildResponse) ProtoMessage() {}

func (x *UploadBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_build_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBuildResponse.ProtoReflect.Descriptor instead.
func (*UploadBuildResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_build_proto_rawDescGZIP(), []int{1}
}

func (x *UploadBuildResponse) GetBuild() *ServerBuild {
	if x != nil {
		return x.Build
	}
	return nil
}

type ListBuildsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int64                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuildsRequest) Reset() {
	*x = ListBuildsRequest{}
	mi := &file_orchestrator_v1_build_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuildsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuildsRequest) ProtoMessage() {}

func (x *ListBuildsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_build_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuildsRequest.ProtoReflect.Descriptor instead.
func (*ListBuildsRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_build_proto_rawDescGZIP(), []int{2}
}

func (x *ListBuildsRequest) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type ListBuildsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Builds        []*ServerBuild         `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuildsResponse) Reset() {
	*x = ListBuildsResponse{}
	mi := &file_orchestrator_v1_build_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuildsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuildsResponse) ProtoMessage() {}

func (x *ListBuildsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_build_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuildsResponse.ProtoReflect.Descriptor instead.
func (*ListBuildsResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_build_proto_rawDescGZIP(), []int{3}
}

func (x *ListBuildsResponse) GetBuilds() []*ServerBuild {
	if x != nil {
		return x.Builds
	}
	return nil
}

type GetBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int64                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	BuildVersion  string                 `protobuf:"bytes,2,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildRequest) Reset() {
	*x = GetBuildRequest{}
	mi := &file_orchestrator_v1_build_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildRequest) ProtoMessage() {}

func (x *GetBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_build_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildRequest.ProtoReflect.Descriptor instead.
func (*GetBuildRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_build_proto_rawDescGZIP(), []int{4}
}

func (x *GetBuildRequest) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GetBuildRequest) GetBuildVersion() string {
	if x != nil {
		return x.BuildVersion
	}
	return ""
}

type GetBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Build         *ServerBuild           `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildResponse) Reset() {
	*x = GetBuildResponse{}
	mi := &file_orchestrator_v1_build_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildResponse) ProtoMessage() {}

func (x *GetBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_build_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildResponse.ProtoReflect.Descriptor instead.
func (*GetBuildResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_build_proto_rawDescGZIP(), []int{5}
}

func (x *GetBuildResponse) GetBuild() *ServerBuild {
	if x != nil {
		return x.Build
	}
	return nil
}

type DeleteBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int64                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	BuildVersion  string                 `protobuf:"bytes,2,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBuildRequest) Reset() {
	*x = DeleteBuildRequest{}
	mi := &file_orchestrator_v1_build_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuildRequest) ProtoMessage() {}

func (x *DeleteBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_build_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuildRequest.ProtoReflect.Descriptor instead.
func (*DeleteBuildRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_build_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBuildRequest) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *DeleteBuildRequest) GetBuildVersion() string {
	if x != nil {
		return x.BuildVersion
	}
	return ""
}

type DeleteBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBuildResponse) Reset() {
	*x = DeleteBuildResponse{}
	mi := &file_orchestrator_v1_build_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuildResponse) ProtoMessage() {}

func (x *DeleteBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_build_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuildResponse.ProtoReflect.Descriptor instead.
func (*DeleteBuildResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_build_proto_rawDescGZIP(), []int{7}
}

var File_orchestrator_v1_build_proto protoreflect.FileDescriptor

const file_orchestrator_v1_build_proto_rawDesc = "" +
	"\n" +
	"\x1borchestrator/v1/build.proto\x12\x0forchestrator.v1\x1a\x1corchestrator/v1/common.proto\"\xee\x01\n" +
	"\x12UploadBuildRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x03R\x06gameId\x12\x1d\n" +
	"\n" +
	"image_data\x18\x02 \x01(\fR\timageData\x12#\n" +
	"\rbuild_version\x18\x03 \x01(\tR\fbuildVersion\x125\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\x19.orchestrator.v1.ProtocolR\bprotocol\x12#\n" +
	"\rinternal_port\x18\x05 \x01(\rR\finternalPort\x12\x1f\n" +
	"\vmax_players\x18\x06 \x01(\rR\n" +
	"maxPlayers\"I\n" +
	"\x13UploadBuildResponse\x122\n" +
	"\x05build\x18\x01 \x01(\v2\x1c.orchestrator.v1.ServerBuildR\x05build\",\n" +
	"\x11ListBuildsRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x03R\x06gameId\"J\n" +
	"\x12ListBuildsResponse\x124\n" +
	"\x06builds\x18\x01 \x03(\v2\x1c.orchestrator.v1.ServerBuildR\x06builds\"O\n" +
	"\x0fGetBuildRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x03R\x06gameId\x12#\n" +
	"\rbuild_version\x18\x02 \x01(\tR\fbuildVersion\"F\n" +
	"\x10GetBuildResponse\x122\n" +
	"\x05build\x18\x01 \x01(\v2\x1c.orchestrator.v1.ServerBuildR\x05build\"R\n" +
	"\x12DeleteBuildRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x03R\x06gameId\x12#\n" +
	"\rbuild_version\x18\x02 \x01(\tR\fbuildVersion\"\x15\n" +
	"\x13DeleteBuildResponse2\xd5\x02\n" +
	"\fBuildService\x12S\n" +
	"\x06Upload\x12#.orchestrator.v1.UploadBuildRequest\x1a$.orchestrator.v1.UploadBuildResponse\x12O\n" +
	"\x04List\x12\".orchestrator.v1.ListBuildsRequest\x1a#.orchestrator.v1.ListBuildsResponse\x12J\n" +
	"\x03Get\x12 .orchestrator.v1.GetBuildRequest\x1a!.orchestrator.v1.GetBuildResponse\x12S\n" +
	"\x06Delete\x12#.orchestrator.v1.DeleteBuildRequest\x1a$.orchestrator.v1.DeleteBuildResponseB\xca\x01\n" +
	"\x13com.orchestrator.v1B\n" +
	"BuildProtoP\x01ZJgithub.com/Be4Die/game-developer-hub/protos/orchestrator/v1;orchestratorv1\xa2\x02\x03OXX\xaa\x02\x0fOrchestrator.V1\xca\x02\x0fOrchestrator\\V1\xe2\x02\x1bOrchestrator\\V1\\GPBMetadata\xea\x02\x10Orchestrator::V1b\x06proto3"

var (
	file_orchestrator_v1_build_proto_rawDescOnce sync.Once
	file_orchestrator_v1_build_proto_rawDescData []byte
)

func file_orchestrator_v1_build_proto_rawDescGZIP() []byte {
	file_orchestrator_v1_build_proto_rawDescOnce.Do(func() {
		file_orchestrator_v1_build_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_v1_build_proto_rawDesc), len(file_orchestrator_v1_build_proto_rawDesc)))
	})
	return file_orchestrator_v1_build_proto_rawDescData
}

var file_orchestrator_v1_build_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_orchestrator_v1_build_proto_goTypes = []any{
	(*UploadBuildRequest)(nil),  // 0: orchestrator.v1.UploadBuildRequest
	(*UploadBuildResponse)(nil), // 1: orchestrator.v1.UploadBuildResponse
	(*ListBuildsRequest)(nil),   // 2: orchestrator.v1.ListBuildsRequest
	(*ListBuildsResponse)(nil),  // 3: orchestrator.v1.ListBuildsResponse
	(*GetBuildRequest)(nil),     // 4: orchestrator.v1.GetBuildRequest
	(*GetBuildResponse)(nil),    // 5: orchestrator.v1.GetBuildResponse
	(*DeleteBuildRequest)(nil),  // 6: orchestrator.v1.DeleteBuildRequest
	(*DeleteBuildResponse)(nil), // 7: orchestrator.v1.DeleteBuildResponse
	(Protocol)(0),               // 8: orchestrator.v1.Protocol
	(*ServerBuild)(nil),         // 9: orchestrator.v1.ServerBuild
}
var file_orchestrator_v1_build_proto_depIdxs = []int32{
	8, // 0: orchestrator.v1.UploadBuildRequest.protocol:type_name -> orchestrator.v1.Protocol
	9, // 1: orchestrator.v1.UploadBuildResponse.build:type_name -> orchestrator.v1.ServerBuild
	9, // 2: orchestrator.v1.ListBuildsResponse.builds:type_name -> orchestrator.v1.ServerBuild
	9, // 3: orchestrator.v1.GetBuildResponse.build:type_name -> orchestrator.v1.ServerBuild
	0, // 4: orchestrator.v1.BuildService.Upload:input_type -> orchestrator.v1.UploadBuildRequest
	2, // 5: orchestrator.v1.BuildService.List:input_type -> orchestrator.v1.ListBuildsRequest
	4, // 6: orchestrator.v1.BuildService.Get:input_type -> orchestrator.v1.GetBuildRequest
	6, // 7: orchestrator.v1.BuildService.Delete:input_type -> orchestrator.v1.DeleteBuildRequest
	1, // 8: orchestrator.v1.BuildService.Upload:output_type -> orchestrator.v1.UploadBuildResponse
	3, // 9: orchestrator.v1.BuildService.List:output_type -> orchestrator.v1.ListBuildsResponse
	5, // 10: orchestrator.v1.BuildService.Get:output_type -> orchestrator.v1.GetBuildResponse
	7, // 11: orchestrator.v1.BuildService.Delete:output_type -> orchestrator.v1.DeleteBuildResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_orchestrator_v1_build_proto_init() }
func file_orchestrator_v1_build_proto_init() {
	if File_orchestrator_v1_build_proto != nil {
		return
	}
	file_orchestrator_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_v1_build_proto_rawDesc), len(file_orchestrator_v1_build_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_v1_build_proto_goTypes,
		DependencyIndexes: file_orchestrator_v1_build_proto_depIdxs,
		MessageInfos:      file_orchestrator_v1_build_proto_msgTypes,
	}.Build()
	File_orchestrator_v1_build_proto = out.File
	file_orchestrator_v1_build_proto_goTypes = nil
	file_orchestrator_v1_build_proto_depIdxs = nil
}
