// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: orchestrator/v1/instance.proto

package orchestratorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InstanceService_Start_FullMethodName      = "/orchestrator.v1.InstanceService/Start"
	InstanceService_List_FullMethodName       = "/orchestrator.v1.InstanceService/List"
	InstanceService_Get_FullMethodName        = "/orchestrator.v1.InstanceService/Get"
	InstanceService_Stop_FullMethodName       = "/orchestrator.v1.InstanceService/Stop"
	InstanceService_StreamLogs_FullMethodName = "/orchestrator.v1.InstanceService/StreamLogs"
	InstanceService_GetUsage_FullMethodName   = "/orchestrator.v1.InstanceService/GetUsage"
)

// InstanceServiceClient is the client API for InstanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис управления инстансами игровых серверов.
type InstanceServiceClient interface {
	// Запустить инстанс сервера.
	Start(ctx context.Context, in *InstanceServiceStartRequest, opts ...grpc.CallOption) (*InstanceServiceStartResponse, error)
	// Список инстансов игры.
	List(ctx context.Context, in *InstanceServiceListRequest, opts ...grpc.CallOption) (*InstanceServiceListResponse, error)
	// Информация об инстансе.
	Get(ctx context.Context, in *InstanceServiceGetRequest, opts ...grpc.CallOption) (*InstanceServiceGetResponse, error)
	// Остановить инстанс.
	Stop(ctx context.Context, in *InstanceServiceStopRequest, opts ...grpc.CallOption) (*InstanceServiceStopResponse, error)
	// Поток журналов инстанса (server streaming) — без HTTP-маппинга.
	StreamLogs(ctx context.Context, in *InstanceServiceStreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstanceServiceStreamLogsResponse], error)
	// Потребление ресурсов инстанса.
	GetUsage(ctx context.Context, in *InstanceServiceGetUsageRequest, opts ...grpc.CallOption) (*InstanceServiceGetUsageResponse, error)
}

type instanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInstanceServiceClient(cc grpc.ClientConnInterface) InstanceServiceClient {
	return &instanceServiceClient{cc}
}

func (c *instanceServiceClient) Start(ctx context.Context, in *InstanceServiceStartRequest, opts ...grpc.CallOption) (*InstanceServiceStartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceServiceStartResponse)
	err := c.cc.Invoke(ctx, InstanceService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceServiceClient) List(ctx context.Context, in *InstanceServiceListRequest, opts ...grpc.CallOption) (*InstanceServiceListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceServiceListResponse)
	err := c.cc.Invoke(ctx, InstanceService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceServiceClient) Get(ctx context.Context, in *InstanceServiceGetRequest, opts ...grpc.CallOption) (*InstanceServiceGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceServiceGetResponse)
	err := c.cc.Invoke(ctx, InstanceService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceServiceClient) Stop(ctx context.Context, in *InstanceServiceStopRequest, opts ...grpc.CallOption) (*InstanceServiceStopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceServiceStopResponse)
	err := c.cc.Invoke(ctx, InstanceService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instanceServiceClient) StreamLogs(ctx context.Context, in *InstanceServiceStreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstanceServiceStreamLogsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InstanceService_ServiceDesc.Streams[0], InstanceService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InstanceServiceStreamLogsRequest, InstanceServiceStreamLogsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InstanceService_StreamLogsClient = grpc.ServerStreamingClient[InstanceServiceStreamLogsResponse]

func (c *instanceServiceClient) GetUsage(ctx context.Context, in *InstanceServiceGetUsageRequest, opts ...grpc.CallOption) (*InstanceServiceGetUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceServiceGetUsageResponse)
	err := c.cc.Invoke(ctx, InstanceService_GetUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstanceServiceServer is the server API for InstanceService service.
// All implementations must embed UnimplementedInstanceServiceServer
// for forward compatibility.
//
// Сервис управления инстансами игровых серверов.
type InstanceServiceServer interface {
	// Запустить инстанс сервера.
	Start(context.Context, *InstanceServiceStartRequest) (*InstanceServiceStartResponse, error)
	// Список инстансов игры.
	List(context.Context, *InstanceServiceListRequest) (*InstanceServiceListResponse, error)
	// Информация об инстансе.
	Get(context.Context, *InstanceServiceGetRequest) (*InstanceServiceGetResponse, error)
	// Остановить инстанс.
	Stop(context.Context, *InstanceServiceStopRequest) (*InstanceServiceStopResponse, error)
	// Поток журналов инстанса (server streaming) — без HTTP-маппинга.
	StreamLogs(*InstanceServiceStreamLogsRequest, grpc.ServerStreamingServer[InstanceServiceStreamLogsResponse]) error
	// Потребление ресурсов инстанса.
	GetUsage(context.Context, *InstanceServiceGetUsageRequest) (*InstanceServiceGetUsageResponse, error)
	mustEmbedUnimplementedInstanceServiceServer()
}

// UnimplementedInstanceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInstanceServiceServer struct{}

func (UnimplementedInstanceServiceServer) Start(context.Context, *InstanceServiceStartRequest) (*InstanceServiceStartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedInstanceServiceServer) List(context.Context, *InstanceServiceListRequest) (*InstanceServiceListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedInstanceServiceServer) Get(context.Context, *InstanceServiceGetRequest) (*InstanceServiceGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedInstanceServiceServer) Stop(context.Context, *InstanceServiceStopRequest) (*InstanceServiceStopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedInstanceServiceServer) StreamLogs(*InstanceServiceStreamLogsRequest, grpc.ServerStreamingServer[InstanceServiceStreamLogsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedInstanceServiceServer) GetUsage(context.Context, *InstanceServiceGetUsageRequest) (*InstanceServiceGetUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsage not implemented")
}
func (UnimplementedInstanceServiceServer) mustEmbedUnimplementedInstanceServiceServer() {}
func (UnimplementedInstanceServiceServer) testEmbeddedByValue()                         {}

// UnsafeInstanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InstanceServiceServer will
// result in compilation errors.
type UnsafeInstanceServiceServer interface {
	mustEmbedUnimplementedInstanceServiceServer()
}

func RegisterInstanceServiceServer(s grpc.ServiceRegistrar, srv InstanceServiceServer) {
	// If the following call panics, it indicates UnimplementedInstanceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InstanceService_ServiceDesc, srv)
}

func _InstanceService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceServiceStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstanceService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServiceServer).Start(ctx, req.(*InstanceServiceStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstanceService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceServiceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstanceService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServiceServer).List(ctx, req.(*InstanceServiceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstanceService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceServiceGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstanceService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServiceServer).Get(ctx, req.(*InstanceServiceGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstanceService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceServiceStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstanceService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServiceServer).Stop(ctx, req.(*InstanceServiceStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstanceService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InstanceServiceStreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InstanceServiceServer).StreamLogs(m, &grpc.GenericServerStream[InstanceServiceStreamLogsRequest, InstanceServiceStreamLogsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InstanceService_StreamLogsServer = grpc.ServerStreamingServer[InstanceServiceStreamLogsResponse]

func _InstanceService_GetUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceServiceGetUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstanceServiceServer).GetUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstanceService_GetUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstanceServiceServer).GetUsage(ctx, req.(*InstanceServiceGetUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InstanceService_ServiceDesc is the grpc.ServiceDesc for InstanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InstanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestrator.v1.InstanceService",
	HandlerType: (*InstanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _InstanceService_Start_Handler,
		},
		{
			MethodName: "List",
			Handler:    _InstanceService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _InstanceService_Get_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _InstanceService_Stop_Handler,
		},
		{
			MethodName: "GetUsage",
			Handler:    _InstanceService_GetUsage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _InstanceService_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "orchestrator/v1/instance.proto",
}
