// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orchestrator/v1/node.proto

package orchestratorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterNodeManual struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Region        *string                `protobuf:"bytes,3,opt,name=region,proto3,oneof" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeManual) Reset() {
	*x = RegisterNodeManual{}
	mi := &file_orchestrator_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeManual) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeManual) ProtoMessage() {}

func (x *RegisterNodeManual) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeManual.ProtoReflect.Descriptor instead.
func (*RegisterNodeManual) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNodeManual) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterNodeManual) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterNodeManual) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

type RegisterNodeAuthorize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeAuthorize) Reset() {
	*x = RegisterNodeAuthorize{}
	mi := &file_orchestrator_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeAuthorize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeAuthorize) ProtoMessage() {}

func (x *RegisterNodeAuthorize) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeAuthorize.ProtoReflect.Descriptor instead.
func (*RegisterNodeAuthorize) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNodeAuthorize) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *RegisterNodeAuthorize) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegisterNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Mode:
	//
	//	*RegisterNodeRequest_Manual
	//	*RegisterNodeRequest_Authorize
	Mode          isRegisterNodeRequest_Mode `protobuf_oneof:"mode"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_orchestrator_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterNodeRequest) GetMode() isRegisterNodeRequest_Mode {
	if x != nil {
		return x.Mode
	}
	return nil
}

func (x *RegisterNodeRequest) GetManual() *RegisterNodeManual {
	if x != nil {
		if x, ok := x.Mode.(*RegisterNodeRequest_Manual); ok {
			return x.Manual
		}
	}
	return nil
}

func (x *RegisterNodeRequest) GetAuthorize() *RegisterNodeAuthorize {
	if x != nil {
		if x, ok := x.Mode.(*RegisterNodeRequest_Authorize); ok {
			return x.Authorize
		}
	}
	return nil
}

type isRegisterNodeRequest_Mode interface {
	isRegisterNodeRequest_Mode()
}

type RegisterNodeRequest_Manual struct {
	Manual *RegisterNodeManual `protobuf:"bytes,1,opt,name=manual,proto3,oneof"`
}

type RegisterNodeRequest_Authorize struct {
	Authorize *RegisterNodeAuthorize `protobuf:"bytes,2,opt,name=authorize,proto3,oneof"`
}

func (*RegisterNodeRequest_Manual) isRegisterNodeRequest_Mode() {}

func (*RegisterNodeRequest_Authorize) isRegisterNodeRequest_Mode() {}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_orchestrator_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *NodeStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=orchestrator.v1.NodeStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_orchestrator_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *ListNodesRequest) GetStatus() NodeStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_orchestrator_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *ListNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_orchestrator_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *GetNodeRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type GetNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeResponse) Reset() {
	*x = GetNodeResponse{}
	mi := &file_orchestrator_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeResponse) ProtoMessage() {}

func (x *GetNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeResponse.ProtoReflect.Descriptor instead.
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *GetNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type DeleteNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeRequest) Reset() {
	*x = DeleteNodeRequest{}
	mi := &file_orchestrator_v1_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeRequest) ProtoMessage() {}

func (x *DeleteNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_node_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteNodeRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type DeleteNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeResponse) Reset() {
	*x = DeleteNodeResponse{}
	mi := &file_orchestrator_v1_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeResponse) ProtoMessage() {}

func (x *DeleteNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeResponse.ProtoReflect.Descriptor instead.
func (*DeleteNodeResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_node_proto_rawDescGZIP(), []int{9}
}

type GetNodeUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeUsageRequest) Reset() {
	*x = GetNodeUsageRequest{}
	mi := &file_orchestrator_v1_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeUsageRequest) ProtoMessage() {}

func (x *GetNodeUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeUsageRequest.ProtoReflect.Descriptor instead.
func (*GetNodeUsageRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_node_proto_rawDescGZIP(), []int{10}
}

func (x *GetNodeUsageRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type GetNodeUsageResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NodeId              int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Usage               *ResourceUsage         `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	ActiveInstanceCount int32                  `protobuf:"varint,3,opt,name=active_instance_count,json=activeInstanceCount,proto3" json:"active_instance_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetNodeUsageResponse) Reset() {
	*x = GetNodeUsageResponse{}
	mi := &file_orchestrator_v1_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeUsageResponse) ProtoMessage() {}

func (x *GetNodeUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_v1_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeUsageResponse.ProtoReflect.Descriptor instead.
func (*GetNodeUsageResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_v1_node_proto_rawDescGZIP(), []int{11}
}

func (x *GetNodeUsageResponse) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *GetNodeUsageResponse) GetUsage() *ResourceUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *GetNodeUsageResponse) GetActiveInstanceCount() int32 {
	if x != nil {
		return x.ActiveInstanceCount
	}
	return 0
}

var File_orchestrator_v1_node_proto protoreflect.FileDescriptor

const file_orchestrator_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x1aorchestrator/v1/node.proto\x12\x0forchestrator.v1\x1a\x1corchestrator/v1/common.proto\"l\n" +
	"\x12RegisterNodeManual\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1b\n" +
	"\x06region\x18\x03 \x01(\tH\x00R\x06region\x88\x01\x01B\t\n" +
	"\a_region\"F\n" +
	"\x15RegisterNodeAuthorize\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\xa4\x01\n" +
	"\x13RegisterNodeRequest\x12=\n" +
	"\x06manual\x18\x01 \x01(\v2#.orchestrator.v1.RegisterNodeManualH\x00R\x06manual\x12F\n" +
	"\tauthorize\x18\x02 \x01(\v2&.orchestrator.v1.RegisterNodeAuthorizeH\x00R\tauthorizeB\x06\n" +
	"\x04mode\"A\n" +
	"\x14RegisterNodeResponse\x12)\n" +
	"\x04node\x18\x01 \x01(\v2\x15.orchestrator.v1.NodeR\x04node\"W\n" +
	"\x10ListNodesRequest\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.orchestrator.v1.NodeStatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"@\n" +
	"\x11ListNodesResponse\x12+\n" +
	"\x05nodes\x18\x01 \x03(\v2\x15.orchestrator.v1.NodeR\x05nodes\")\n" +
	"\x0eGetNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\"<\n" +
	"\x0fGetNodeResponse\x12)\n" +
	"\x04node\x18\x01 \x01(\v2\x15.orchestrator.v1.NodeR\x04node\",\n" +
	"\x11DeleteNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\"\x14\n" +
	"\x12DeleteNodeResponse\".\n" +
	"\x13GetNodeUsageRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\"\x99\x01\n" +
	"\x14GetNodeUsageResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x124\n" +
	"\x05usage\x18\x02 \x01(\v2\x1e.orchestrator.v1.ResourceUsageR\x05usage\x122\n" +
	"\x15active_instance_count\x18\x03 \x01(\x05R\x13activeInstanceCount2\xab\x03\n" +
	"\vNodeService\x12W\n" +
	"\bRegister\x12$.orchestrator.v1.RegisterNodeRequest\x1a%.orchestrator.v1.RegisterNodeResponse\x12M\n" +
	"\x04List\x12!.orchestrator.v1.ListNodesRequest\x1a\".orchestrator.v1.ListNodesResponse\x12H\n" +
	"\x03Get\x12\x1f.orchestrator.v1.GetNodeRequest\x1a .orchestrator.v1.GetNodeResponse\x12Q\n" +
	"\x06Delete\x12\".orchestrator.v1.DeleteNodeRequest\x1a#.orchestrator.v1.DeleteNodeResponse\x12W\n" +
	"\bGetUsage\x12$.orchestrator.v1.GetNodeUsageRequest\x1a%.orchestrator.v1.GetNodeUsageResponseB\xc9\x01\n" +
	"\x13com.orchestrator.v1B\tNodeProtoP\x01ZJgithub.com/Be4Die/game-developer-hub/protos/orchestrator/v1;orchestratorv1\xa2\x02\x03OXX\xaa\x02\x0fOrchestrator.V1\xca\x02\x0fOrchestrator\\V1\xe2\x02\x1bOrchestrator\\V1\\GPBMetadata\xea\x02\x10Orchestrator::V1b\x06proto3"

var (
	file_orchestrator_v1_node_proto_rawDescOnce sync.Once
	file_orchestrator_v1_node_proto_rawDescData []byte
)

func file_orchestrator_v1_node_proto_rawDescGZIP() []byte {
	file_orchestrator_v1_node_proto_rawDescOnce.Do(func() {
		file_orchestrator_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_v1_node_proto_rawDesc), len(file_orchestrator_v1_node_proto_rawDesc)))
	})
	return file_orchestrator_v1_node_proto_rawDescData
}

var file_orchestrator_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_orchestrator_v1_node_proto_goTypes = []any{
	(*RegisterNodeManual)(nil),    // 0: orchestrator.v1.RegisterNodeManual
	(*RegisterNodeAuthorize)(nil), // 1: orchestrator.v1.RegisterNodeAuthorize
	(*RegisterNodeRequest)(nil),   // 2: orchestrator.v1.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),  // 3: orchestrator.v1.RegisterNodeResponse
	(*ListNodesRequest)(nil),      // 4: orchestrator.v1.ListNodesRequest
	(*ListNodesResponse)(nil),     // 5: orchestrator.v1.ListNodesResponse
	(*GetNodeRequest)(nil),        // 6: orchestrator.v1.GetNodeRequest
	(*GetNodeResponse)(nil),       // 7: orchestrator.v1.GetNodeResponse
	(*DeleteNodeRequest)(nil),     // 8: orchestrator.v1.DeleteNodeRequest
	(*DeleteNodeResponse)(nil),    // 9: orchestrator.v1.DeleteNodeResponse
	(*GetNodeUsageRequest)(nil),   // 10: orchestrator.v1.GetNodeUsageRequest
	(*GetNodeUsageResponse)(nil),  // 11: orchestrator.v1.GetNodeUsageResponse
	(*Node)(nil),                  // 12: orchestrator.v1.Node
	(NodeStatus)(0),               // 13: orchestrator.v1.NodeStatus
	(*ResourceUsage)(nil),         // 14: orchestrator.v1.ResourceUsage
}
var file_orchestrator_v1_node_proto_depIdxs = []int32{
	0,  // 0: orchestrator.v1.RegisterNodeRequest.manual:type_name -> orchestrator.v1.RegisterNodeManual
	1,  // 1: orchestrator.v1.RegisterNodeRequest.authorize:type_name -> orchestrator.v1.RegisterNodeAuthorize
	12, // 2: orchestrator.v1.RegisterNodeResponse.node:type_name -> orchestrator.v1.Node
	13, // 3: orchestrator.v1.ListNodesRequest.status:type_name -> orchestrator.v1.NodeStatus
	12, // 4: orchestrator.v1.ListNodesResponse.nodes:type_name -> orchestrator.v1.Node
	12, // 5: orchestrator.v1.GetNodeResponse.node:type_name -> orchestrator.v1.Node
	14, // 6: orchestrator.v1.GetNodeUsageResponse.usage:type_name -> orchestrator.v1.ResourceUsage
	2,  // 7: orchestrator.v1.NodeService.Register:input_type -> orchestrator.v1.RegisterNodeRequest
	4,  // 8: orchestrator.v1.NodeService.List:input_type -> orchestrator.v1.ListNodesRequest
	6,  // 9: orchestrator.v1.NodeService.Get:input_type -> orchestrator.v1.GetNodeRequest
	8,  // 10: orchestrator.v1.NodeService.Delete:input_type -> orchestrator.v1.DeleteNodeRequest
	10, // 11: orchestrator.v1.NodeService.GetUsage:input_type -> orchestrator.v1.GetNodeUsageRequest
	3,  // 12: orchestrator.v1.NodeService.Register:output_type -> orchestrator.v1.RegisterNodeResponse
	5,  // 13: orchestrator.v1.NodeService.List:output_type -> orchestrator.v1.ListNodesResponse
	7,  // 14: orchestrator.v1.NodeService.Get:output_type -> orchestrator.v1.GetNodeResponse
	9,  // 15: orchestrator.v1.NodeService.Delete:output_type -> orchestrator.v1.DeleteNodeResponse
	11, // 16: orchestrator.v1.NodeService.GetUsage:output_type -> orchestrator.v1.GetNodeUsageResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_orchestrator_v1_node_proto_init() }
func file_orchestrator_v1_node_proto_init() {
	if File_orchestrator_v1_node_proto != nil {
		return
	}
	file_orchestrator_v1_common_proto_init()
	file_orchestrator_v1_node_proto_msgTypes[0].OneofWrappers = []any{}
	file_orchestrator_v1_node_proto_msgTypes[2].OneofWrappers = []any{
		(*RegisterNodeRequest_Manual)(nil),
		(*RegisterNodeRequest_Authorize)(nil),
	}
	file_orchestrator_v1_node_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_v1_node_proto_rawDesc), len(file_orchestrator_v1_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_v1_node_proto_goTypes,
		DependencyIndexes: file_orchestrator_v1_node_proto_depIdxs,
		MessageInfos:      file_orchestrator_v1_node_proto_msgTypes,
	}.Build()
	File_orchestrator_v1_node_proto = out.File
	file_orchestrator_v1_node_proto_goTypes = nil
	file_orchestrator_v1_node_proto_depIdxs = nil
}
