// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: project_manager/v1/project.proto

package project_managerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProjectService_Create_FullMethodName              = "/project_manager.v1.ProjectService/Create"
	ProjectService_Get_FullMethodName                 = "/project_manager.v1.ProjectService/Get"
	ProjectService_List_FullMethodName                = "/project_manager.v1.ProjectService/List"
	ProjectService_Update_FullMethodName              = "/project_manager.v1.ProjectService/Update"
	ProjectService_Delete_FullMethodName              = "/project_manager.v1.ProjectService/Delete"
	ProjectService_UploadBuild_FullMethodName         = "/project_manager.v1.ProjectService/UploadBuild"
	ProjectService_UploadBuildStream_FullMethodName   = "/project_manager.v1.ProjectService/UploadBuildStream"
	ProjectService_ListBuilds_FullMethodName          = "/project_manager.v1.ProjectService/ListBuilds"
	ProjectService_DeleteBuild_FullMethodName         = "/project_manager.v1.ProjectService/DeleteBuild"
	ProjectService_UploadMedia_FullMethodName         = "/project_manager.v1.ProjectService/UploadMedia"
	ProjectService_UploadMediaStream_FullMethodName   = "/project_manager.v1.ProjectService/UploadMediaStream"
	ProjectService_SubmitForModeration_FullMethodName = "/project_manager.v1.ProjectService/SubmitForModeration"
	ProjectService_PublishRelease_FullMethodName      = "/project_manager.v1.ProjectService/PublishRelease"
	ProjectService_RejectDraft_FullMethodName         = "/project_manager.v1.ProjectService/RejectDraft"
	ProjectService_GetPublished_FullMethodName        = "/project_manager.v1.ProjectService/GetPublished"
	ProjectService_Unpublish_FullMethodName           = "/project_manager.v1.ProjectService/Unpublish"
)

// ProjectServiceClient is the client API for ProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjectServiceClient interface {
	Create(ctx context.Context, in *ProjectCreateRequest, opts ...grpc.CallOption) (*ProjectCreateResponse, error)
	Get(ctx context.Context, in *ProjectGetRequest, opts ...grpc.CallOption) (*ProjectGetResponse, error)
	List(ctx context.Context, in *ProjectListRequest, opts ...grpc.CallOption) (*ProjectListResponse, error)
	Update(ctx context.Context, in *ProjectUpdateRequest, opts ...grpc.CallOption) (*ProjectUpdateResponse, error)
	Delete(ctx context.Context, in *ProjectDeleteRequest, opts ...grpc.CallOption) (*ProjectDeleteResponse, error)
	// Загрузка сборок
	UploadBuild(ctx context.Context, in *ProjectUploadBuildRequest, opts ...grpc.CallOption) (*ProjectUploadBuildResponse, error)
	UploadBuildStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ProjectUploadBuildStreamRequest, ProjectUploadBuildResponse], error)
	ListBuilds(ctx context.Context, in *ProjectListBuildsRequest, opts ...grpc.CallOption) (*ProjectListBuildsResponse, error)
	DeleteBuild(ctx context.Context, in *ProjectDeleteBuildRequest, opts ...grpc.CallOption) (*ProjectDeleteBuildResponse, error)
	// Загрузка медиа
	UploadMedia(ctx context.Context, in *ProjectUploadMediaRequest, opts ...grpc.CallOption) (*ProjectUploadMediaResponse, error)
	UploadMediaStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ProjectUploadMediaStreamRequest, ProjectUploadMediaResponse], error)
	// Модерация и публикация
	SubmitForModeration(ctx context.Context, in *SubmitForModerationRequest, opts ...grpc.CallOption) (*SubmitForModerationResponse, error)
	PublishRelease(ctx context.Context, in *ProjectPublishReleaseRequest, opts ...grpc.CallOption) (*ProjectPublishReleaseResponse, error)
	RejectDraft(ctx context.Context, in *ProjectRejectDraftRequest, opts ...grpc.CallOption) (*ProjectRejectDraftResponse, error)
	GetPublished(ctx context.Context, in *ProjectGetPublishedRequest, opts ...grpc.CallOption) (*ProjectGetPublishedResponse, error)
	Unpublish(ctx context.Context, in *ProjectUnpublishRequest, opts ...grpc.CallOption) (*ProjectUnpublishResponse, error)
}

type projectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectServiceClient(cc grpc.ClientConnInterface) ProjectServiceClient {
	return &projectServiceClient{cc}
}

func (c *projectServiceClient) Create(ctx context.Context, in *ProjectCreateRequest, opts ...grpc.CallOption) (*ProjectCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectCreateResponse)
	err := c.cc.Invoke(ctx, ProjectService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Get(ctx context.Context, in *ProjectGetRequest, opts ...grpc.CallOption) (*ProjectGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectGetResponse)
	err := c.cc.Invoke(ctx, ProjectService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) List(ctx context.Context, in *ProjectListRequest, opts ...grpc.CallOption) (*ProjectListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectListResponse)
	err := c.cc.Invoke(ctx, ProjectService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Update(ctx context.Context, in *ProjectUpdateRequest, opts ...grpc.CallOption) (*ProjectUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectUpdateResponse)
	err := c.cc.Invoke(ctx, ProjectService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Delete(ctx context.Context, in *ProjectDeleteRequest, opts ...grpc.CallOption) (*ProjectDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectDeleteResponse)
	err := c.cc.Invoke(ctx, ProjectService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UploadBuild(ctx context.Context, in *ProjectUploadBuildRequest, opts ...grpc.CallOption) (*ProjectUploadBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectUploadBuildResponse)
	err := c.cc.Invoke(ctx, ProjectService_UploadBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UploadBuildStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ProjectUploadBuildStreamRequest, ProjectUploadBuildResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProjectService_ServiceDesc.Streams[0], ProjectService_UploadBuildStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProjectUploadBuildStreamRequest, ProjectUploadBuildResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProjectService_UploadBuildStreamClient = grpc.ClientStreamingClient[ProjectUploadBuildStreamRequest, ProjectUploadBuildResponse]

func (c *projectServiceClient) ListBuilds(ctx context.Context, in *ProjectListBuildsRequest, opts ...grpc.CallOption) (*ProjectListBuildsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectListBuildsResponse)
	err := c.cc.Invoke(ctx, ProjectService_ListBuilds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) DeleteBuild(ctx context.Context, in *ProjectDeleteBuildRequest, opts ...grpc.CallOption) (*ProjectDeleteBuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectDeleteBuildResponse)
	err := c.cc.Invoke(ctx, ProjectService_DeleteBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UploadMedia(ctx context.Context, in *ProjectUploadMediaRequest, opts ...grpc.CallOption) (*ProjectUploadMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectUploadMediaResponse)
	err := c.cc.Invoke(ctx, ProjectService_UploadMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UploadMediaStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ProjectUploadMediaStreamRequest, ProjectUploadMediaResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProjectService_ServiceDesc.Streams[1], ProjectService_UploadMediaStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProjectUploadMediaStreamRequest, ProjectUploadMediaResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProjectService_UploadMediaStreamClient = grpc.ClientStreamingClient[ProjectUploadMediaStreamRequest, ProjectUploadMediaResponse]

func (c *projectServiceClient) SubmitForModeration(ctx context.Context, in *SubmitForModerationRequest, opts ...grpc.CallOption) (*SubmitForModerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitForModerationResponse)
	err := c.cc.Invoke(ctx, ProjectService_SubmitForModeration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) PublishRelease(ctx context.Context, in *ProjectPublishReleaseRequest, opts ...grpc.CallOption) (*ProjectPublishReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectPublishReleaseResponse)
	err := c.cc.Invoke(ctx, ProjectService_PublishRelease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) RejectDraft(ctx context.Context, in *ProjectRejectDraftRequest, opts ...grpc.CallOption) (*ProjectRejectDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectRejectDraftResponse)
	err := c.cc.Invoke(ctx, ProjectService_RejectDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetPublished(ctx context.Context, in *ProjectGetPublishedRequest, opts ...grpc.CallOption) (*ProjectGetPublishedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectGetPublishedResponse)
	err := c.cc.Invoke(ctx, ProjectService_GetPublished_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Unpublish(ctx context.Context, in *ProjectUnpublishRequest, opts ...grpc.CallOption) (*ProjectUnpublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectUnpublishResponse)
	err := c.cc.Invoke(ctx, ProjectService_Unpublish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServiceServer is the server API for ProjectService service.
// All implementations must embed UnimplementedProjectServiceServer
// for forward compatibility.
type ProjectServiceServer interface {
	Create(context.Context, *ProjectCreateRequest) (*ProjectCreateResponse, error)
	Get(context.Context, *ProjectGetRequest) (*ProjectGetResponse, error)
	List(context.Context, *ProjectListRequest) (*ProjectListResponse, error)
	Update(context.Context, *ProjectUpdateRequest) (*ProjectUpdateResponse, error)
	Delete(context.Context, *ProjectDeleteRequest) (*ProjectDeleteResponse, error)
	// Загрузка сборок
	UploadBuild(context.Context, *ProjectUploadBuildRequest) (*ProjectUploadBuildResponse, error)
	UploadBuildStream(grpc.ClientStreamingServer[ProjectUploadBuildStreamRequest, ProjectUploadBuildResponse]) error
	ListBuilds(context.Context, *ProjectListBuildsRequest) (*ProjectListBuildsResponse, error)
	DeleteBuild(context.Context, *ProjectDeleteBuildRequest) (*ProjectDeleteBuildResponse, error)
	// Загрузка медиа
	UploadMedia(context.Context, *ProjectUploadMediaRequest) (*ProjectUploadMediaResponse, error)
	UploadMediaStream(grpc.ClientStreamingServer[ProjectUploadMediaStreamRequest, ProjectUploadMediaResponse]) error
	// Модерация и публикация
	SubmitForModeration(context.Context, *SubmitForModerationRequest) (*SubmitForModerationResponse, error)
	PublishRelease(context.Context, *ProjectPublishReleaseRequest) (*ProjectPublishReleaseResponse, error)
	RejectDraft(context.Context, *ProjectRejectDraftRequest) (*ProjectRejectDraftResponse, error)
	GetPublished(context.Context, *ProjectGetPublishedRequest) (*ProjectGetPublishedResponse, error)
	Unpublish(context.Context, *ProjectUnpublishRequest) (*ProjectUnpublishResponse, error)
	mustEmbedUnimplementedProjectServiceServer()
}

// UnimplementedProjectServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectServiceServer struct{}

func (UnimplementedProjectServiceServer) Create(context.Context, *ProjectCreateRequest) (*ProjectCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedProjectServiceServer) Get(context.Context, *ProjectGetRequest) (*ProjectGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedProjectServiceServer) List(context.Context, *ProjectListRequest) (*ProjectListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedProjectServiceServer) Update(context.Context, *ProjectUpdateRequest) (*ProjectUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedProjectServiceServer) Delete(context.Context, *ProjectDeleteRequest) (*ProjectDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedProjectServiceServer) UploadBuild(context.Context, *ProjectUploadBuildRequest) (*ProjectUploadBuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadBuild not implemented")
}
func (UnimplementedProjectServiceServer) UploadBuildStream(grpc.ClientStreamingServer[ProjectUploadBuildStreamRequest, ProjectUploadBuildResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadBuildStream not implemented")
}
func (UnimplementedProjectServiceServer) ListBuilds(context.Context, *ProjectListBuildsRequest) (*ProjectListBuildsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBuilds not implemented")
}
func (UnimplementedProjectServiceServer) DeleteBuild(context.Context, *ProjectDeleteBuildRequest) (*ProjectDeleteBuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBuild not implemented")
}
func (UnimplementedProjectServiceServer) UploadMedia(context.Context, *ProjectUploadMediaRequest) (*ProjectUploadMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadMedia not implemented")
}
func (UnimplementedProjectServiceServer) UploadMediaStream(grpc.ClientStreamingServer[ProjectUploadMediaStreamRequest, ProjectUploadMediaResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadMediaStream not implemented")
}
func (UnimplementedProjectServiceServer) SubmitForModeration(context.Context, *SubmitForModerationRequest) (*SubmitForModerationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitForModeration not implemented")
}
func (UnimplementedProjectServiceServer) PublishRelease(context.Context, *ProjectPublishReleaseRequest) (*ProjectPublishReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishRelease not implemented")
}
func (UnimplementedProjectServiceServer) RejectDraft(context.Context, *ProjectRejectDraftRequest) (*ProjectRejectDraftResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectDraft not implemented")
}
func (UnimplementedProjectServiceServer) GetPublished(context.Context, *ProjectGetPublishedRequest) (*ProjectGetPublishedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublished not implemented")
}
func (UnimplementedProjectServiceServer) Unpublish(context.Context, *ProjectUnpublishRequest) (*ProjectUnpublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unpublish not implemented")
}
func (UnimplementedProjectServiceServer) mustEmbedUnimplementedProjectServiceServer() {}
func (UnimplementedProjectServiceServer) testEmbeddedByValue()                        {}

// UnsafeProjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectServiceServer will
// result in compilation errors.
type UnsafeProjectServiceServer interface {
	mustEmbedUnimplementedProjectServiceServer()
}

func RegisterProjectServiceServer(s grpc.ServiceRegistrar, srv ProjectServiceServer) {
	// If the following call panics, it indicates UnimplementedProjectServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectService_ServiceDesc, srv)
}

func _ProjectService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Create(ctx, req.(*ProjectCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Get(ctx, req.(*ProjectGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).List(ctx, req.(*ProjectListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Update(ctx, req.(*ProjectUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Delete(ctx, req.(*ProjectDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UploadBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectUploadBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UploadBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_UploadBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UploadBuild(ctx, req.(*ProjectUploadBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UploadBuildStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProjectServiceServer).UploadBuildStream(&grpc.GenericServerStream[ProjectUploadBuildStreamRequest, ProjectUploadBuildResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProjectService_UploadBuildStreamServer = grpc.ClientStreamingServer[ProjectUploadBuildStreamRequest, ProjectUploadBuildResponse]

func _ProjectService_ListBuilds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectListBuildsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).ListBuilds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_ListBuilds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).ListBuilds(ctx, req.(*ProjectListBuildsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_DeleteBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectDeleteBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).DeleteBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_DeleteBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).DeleteBuild(ctx, req.(*ProjectDeleteBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UploadMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectUploadMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UploadMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_UploadMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UploadMedia(ctx, req.(*ProjectUploadMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UploadMediaStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProjectServiceServer).UploadMediaStream(&grpc.GenericServerStream[ProjectUploadMediaStreamRequest, ProjectUploadMediaResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProjectService_UploadMediaStreamServer = grpc.ClientStreamingServer[ProjectUploadMediaStreamRequest, ProjectUploadMediaResponse]

func _ProjectService_SubmitForModeration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitForModerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).SubmitForModeration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_SubmitForModeration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).SubmitForModeration(ctx, req.(*SubmitForModerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_PublishRelease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectPublishReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).PublishRelease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_PublishRelease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).PublishRelease(ctx, req.(*ProjectPublishReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_RejectDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRejectDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).RejectDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_RejectDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).RejectDraft(ctx, req.(*ProjectRejectDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetPublished_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectGetPublishedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetPublished(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetPublished_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetPublished(ctx, req.(*ProjectGetPublishedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Unpublish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectUnpublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Unpublish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_Unpublish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Unpublish(ctx, req.(*ProjectUnpublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectService_ServiceDesc is the grpc.ServiceDesc for ProjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "project_manager.v1.ProjectService",
	HandlerType: (*ProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProjectService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ProjectService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ProjectService_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProjectService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ProjectService_Delete_Handler,
		},
		{
			MethodName: "UploadBuild",
			Handler:    _ProjectService_UploadBuild_Handler,
		},
		{
			MethodName: "ListBuilds",
			Handler:    _ProjectService_ListBuilds_Handler,
		},
		{
			MethodName: "DeleteBuild",
			Handler:    _ProjectService_DeleteBuild_Handler,
		},
		{
			MethodName: "UploadMedia",
			Handler:    _ProjectService_UploadMedia_Handler,
		},
		{
			MethodName: "SubmitForModeration",
			Handler:    _ProjectService_SubmitForModeration_Handler,
		},
		{
			MethodName: "PublishRelease",
			Handler:    _ProjectService_PublishRelease_Handler,
		},
		{
			MethodName: "RejectDraft",
			Handler:    _ProjectService_RejectDraft_Handler,
		},
		{
			MethodName: "GetPublished",
			Handler:    _ProjectService_GetPublished_Handler,
		},
		{
			MethodName: "Unpublish",
			Handler:    _ProjectService_Unpublish_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadBuildStream",
			Handler:       _ProjectService_UploadBuildStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadMediaStream",
			Handler:       _ProjectService_UploadMediaStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "project_manager/v1/project.proto",
}
