// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sso/v1/user.proto

package ssov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Извлекается из JWT, поле может быть пустым.
	UserId        string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_sso_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_sso_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   *string                `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_sso_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProfileRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_sso_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProfileResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ChangePasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentPassword string                 `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword     string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_sso_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *ChangePasswordRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_sso_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *ChangePasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUserByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdRequest) Reset() {
	*x = GetUserByIdRequest{}
	mi := &file_sso_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdRequest) ProtoMessage() {}

func (x *GetUserByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserByIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdResponse) Reset() {
	*x = GetUserByIdResponse{}
	mi := &file_sso_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdResponse) ProtoMessage() {}

func (x *GetUserByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIdResponse) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserByIdResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type SearchUsersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Поисковый запрос (совпадение по email или display_name).
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Лимит результатов (по умолчанию 20, максимум 100).
	Limit *int32 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	// Смещение для пагинации.
	Offset        *int32 `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_sso_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *SearchUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUsersRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *SearchUsersRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type SearchUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResponse) Reset() {
	*x = SearchUsersResponse{}
	mi := &file_sso_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResponse) ProtoMessage() {}

func (x *SearchUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResponse.ProtoReflect.Descriptor instead.
func (*SearchUsersResponse) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *SearchUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SearchUsersResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ChangeUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewRole       UserRole               `protobuf:"varint,2,opt,name=new_role,json=newRole,proto3,enum=sso.v1.UserRole" json:"new_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserRoleRequest) Reset() {
	*x = ChangeUserRoleRequest{}
	mi := &file_sso_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserRoleRequest) ProtoMessage() {}

func (x *ChangeUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserRoleRequest.ProtoReflect.Descriptor instead.
func (*ChangeUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *ChangeUserRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangeUserRoleRequest) GetNewRole() UserRole {
	if x != nil {
		return x.NewRole
	}
	return UserRole_USER_ROLE_UNSPECIFIED
}

type ChangeUserRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeUserRoleResponse) Reset() {
	*x = ChangeUserRoleResponse{}
	mi := &file_sso_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeUserRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserRoleResponse) ProtoMessage() {}

func (x *ChangeUserRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserRoleResponse.ProtoReflect.Descriptor instead.
func (*ChangeUserRoleResponse) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeUserRoleResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type SetUserStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewStatus     UserStatus             `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=sso.v1.UserStatus" json:"new_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserStatusRequest) Reset() {
	*x = SetUserStatusRequest{}
	mi := &file_sso_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserStatusRequest) ProtoMessage() {}

func (x *SetUserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserStatusRequest.ProtoReflect.Descriptor instead.
func (*SetUserStatusRequest) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *SetUserStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetUserStatusRequest) GetNewStatus() UserStatus {
	if x != nil {
		return x.NewStatus
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

type SetUserStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserStatusResponse) Reset() {
	*x = SetUserStatusResponse{}
	mi := &file_sso_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserStatusResponse) ProtoMessage() {}

func (x *SetUserStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserStatusResponse.ProtoReflect.Descriptor instead.
func (*SetUserStatusResponse) Descriptor() ([]byte, []int) {
	return file_sso_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *SetUserStatusResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_sso_v1_user_proto protoreflect.FileDescriptor

const file_sso_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x11sso/v1/user.proto\x12\x06sso.v1\x1a\x13sso/v1/common.proto\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"6\n" +
	"\x12GetProfileResponse\x12 \n" +
	"\x04user\x18\x01 \x01(\v2\f.sso.v1.UserR\x04user\"O\n" +
	"\x14UpdateProfileRequest\x12&\n" +
	"\fdisplay_name\x18\x01 \x01(\tH\x00R\vdisplayName\x88\x01\x01B\x0f\n" +
	"\r_display_name\"9\n" +
	"\x15UpdateProfileResponse\x12 \n" +
	"\x04user\x18\x01 \x01(\v2\f.sso.v1.UserR\x04user\"e\n" +
	"\x15ChangePasswordRequest\x12)\n" +
	"\x10current_password\x18\x01 \x01(\tR\x0fcurrentPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"2\n" +
	"\x16ChangePasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x12GetUserByIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"7\n" +
	"\x13GetUserByIdResponse\x12 \n" +
	"\x04user\x18\x01 \x01(\v2\f.sso.v1.UserR\x04user\"w\n" +
	"\x12SearchUsersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x05H\x01R\x06offset\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"Z\n" +
	"\x13SearchUsersResponse\x12\"\n" +
	"\x05users\x18\x01 \x03(\v2\f.sso.v1.UserR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"]\n" +
	"\x15ChangeUserRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\bnew_role\x18\x02 \x01(\x0e2\x10.sso.v1.UserRoleR\anewRole\":\n" +
	"\x16ChangeUserRoleResponse\x12 \n" +
	"\x04user\x18\x01 \x01(\v2\f.sso.v1.UserR\x04user\"b\n" +
	"\x14SetUserStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x121\n" +
	"\n" +
	"new_status\x18\x02 \x01(\x0e2\x12.sso.v1.UserStatusR\tnewStatus\"9\n" +
	"\x15SetUserStatusResponse\x12 \n" +
	"\x04user\x18\x01 \x01(\v2\f.sso.v1.UserR\x04user2\xa0\x04\n" +
	"\vUserService\x12C\n" +
	"\n" +
	"GetProfile\x12\x19.sso.v1.GetProfileRequest\x1a\x1a.sso.v1.GetProfileResponse\x12L\n" +
	"\rUpdateProfile\x12\x1c.sso.v1.UpdateProfileRequest\x1a\x1d.sso.v1.UpdateProfileResponse\x12O\n" +
	"\x0eChangePassword\x12\x1d.sso.v1.ChangePasswordRequest\x1a\x1e.sso.v1.ChangePasswordResponse\x12F\n" +
	"\vGetUserById\x12\x1a.sso.v1.GetUserByIdRequest\x1a\x1b.sso.v1.GetUserByIdResponse\x12F\n" +
	"\vSearchUsers\x12\x1a.sso.v1.SearchUsersRequest\x1a\x1b.sso.v1.SearchUsersResponse\x12O\n" +
	"\x0eChangeUserRole\x12\x1d.sso.v1.ChangeUserRoleRequest\x1a\x1e.sso.v1.ChangeUserRoleResponse\x12L\n" +
	"\rSetUserStatus\x12\x1c.sso.v1.SetUserStatusRequest\x1a\x1d.sso.v1.SetUserStatusResponseB\x8a\x01\n" +
	"\n" +
	"com.sso.v1B\tUserProtoP\x01Z8github.com/Be4Die/game-developer-hub/protos/sso/v1;ssov1\xa2\x02\x03SXX\xaa\x02\x06Sso.V1\xca\x02\x06Sso\\V1\xe2\x02\x12Sso\\V1\\GPBMetadata\xea\x02\aSso::V1b\x06proto3"

var (
	file_sso_v1_user_proto_rawDescOnce sync.Once
	file_sso_v1_user_proto_rawDescData []byte
)

func file_sso_v1_user_proto_rawDescGZIP() []byte {
	file_sso_v1_user_proto_rawDescOnce.Do(func() {
		file_sso_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sso_v1_user_proto_rawDesc), len(file_sso_v1_user_proto_rawDesc)))
	})
	return file_sso_v1_user_proto_rawDescData
}

var file_sso_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_sso_v1_user_proto_goTypes = []any{
	(*GetProfileRequest)(nil),      // 0: sso.v1.GetProfileRequest
	(*GetProfileResponse)(nil),     // 1: sso.v1.GetProfileResponse
	(*UpdateProfileRequest)(nil),   // 2: sso.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),  // 3: sso.v1.UpdateProfileResponse
	(*ChangePasswordRequest)(nil),  // 4: sso.v1.ChangePasswordRequest
	(*ChangePasswordResponse)(nil), // 5: sso.v1.ChangePasswordResponse
	(*GetUserByIdRequest)(nil),     // 6: sso.v1.GetUserByIdRequest
	(*GetUserByIdResponse)(nil),    // 7: sso.v1.GetUserByIdResponse
	(*SearchUsersRequest)(nil),     // 8: sso.v1.SearchUsersRequest
	(*SearchUsersResponse)(nil),    // 9: sso.v1.SearchUsersResponse
	(*ChangeUserRoleRequest)(nil),  // 10: sso.v1.ChangeUserRoleRequest
	(*ChangeUserRoleResponse)(nil), // 11: sso.v1.ChangeUserRoleResponse
	(*SetUserStatusRequest)(nil),   // 12: sso.v1.SetUserStatusRequest
	(*SetUserStatusResponse)(nil),  // 13: sso.v1.SetUserStatusResponse
	(*User)(nil),                   // 14: sso.v1.User
	(UserRole)(0),                  // 15: sso.v1.UserRole
	(UserStatus)(0),                // 16: sso.v1.UserStatus
}
var file_sso_v1_user_proto_depIdxs = []int32{
	14, // 0: sso.v1.GetProfileResponse.user:type_name -> sso.v1.User
	14, // 1: sso.v1.UpdateProfileResponse.user:type_name -> sso.v1.User
	14, // 2: sso.v1.GetUserByIdResponse.user:type_name -> sso.v1.User
	14, // 3: sso.v1.SearchUsersResponse.users:type_name -> sso.v1.User
	15, // 4: sso.v1.ChangeUserRoleRequest.new_role:type_name -> sso.v1.UserRole
	14, // 5: sso.v1.ChangeUserRoleResponse.user:type_name -> sso.v1.User
	16, // 6: sso.v1.SetUserStatusRequest.new_status:type_name -> sso.v1.UserStatus
	14, // 7: sso.v1.SetUserStatusResponse.user:type_name -> sso.v1.User
	0,  // 8: sso.v1.UserService.GetProfile:input_type -> sso.v1.GetProfileRequest
	2,  // 9: sso.v1.UserService.UpdateProfile:input_type -> sso.v1.UpdateProfileRequest
	4,  // 10: sso.v1.UserService.ChangePassword:input_type -> sso.v1.ChangePasswordRequest
	6,  // 11: sso.v1.UserService.GetUserById:input_type -> sso.v1.GetUserByIdRequest
	8,  // 12: sso.v1.UserService.SearchUsers:input_type -> sso.v1.SearchUsersRequest
	10, // 13: sso.v1.UserService.ChangeUserRole:input_type -> sso.v1.ChangeUserRoleRequest
	12, // 14: sso.v1.UserService.SetUserStatus:input_type -> sso.v1.SetUserStatusRequest
	1,  // 15: sso.v1.UserService.GetProfile:output_type -> sso.v1.GetProfileResponse
	3,  // 16: sso.v1.UserService.UpdateProfile:output_type -> sso.v1.UpdateProfileResponse
	5,  // 17: sso.v1.UserService.ChangePassword:output_type -> sso.v1.ChangePasswordResponse
	7,  // 18: sso.v1.UserService.GetUserById:output_type -> sso.v1.GetUserByIdResponse
	9,  // 19: sso.v1.UserService.SearchUsers:output_type -> sso.v1.SearchUsersResponse
	11, // 20: sso.v1.UserService.ChangeUserRole:output_type -> sso.v1.ChangeUserRoleResponse
	13, // 21: sso.v1.UserService.SetUserStatus:output_type -> sso.v1.SetUserStatusResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_sso_v1_user_proto_init() }
func file_sso_v1_user_proto_init() {
	if File_sso_v1_user_proto != nil {
		return
	}
	file_sso_v1_common_proto_init()
	file_sso_v1_user_proto_msgTypes[2].OneofWrappers = []any{}
	file_sso_v1_user_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sso_v1_user_proto_rawDesc), len(file_sso_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sso_v1_user_proto_goTypes,
		DependencyIndexes: file_sso_v1_user_proto_depIdxs,
		MessageInfos:      file_sso_v1_user_proto_msgTypes,
	}.Build()
	File_sso_v1_user_proto = out.File
	file_sso_v1_user_proto_goTypes = nil
	file_sso_v1_user_proto_depIdxs = nil
}
