// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: sso/v1/user.proto

package ssov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_GetProfile_FullMethodName      = "/sso.v1.UserService/GetProfile"
	UserService_UpdateProfile_FullMethodName   = "/sso.v1.UserService/UpdateProfile"
	UserService_ChangePassword_FullMethodName  = "/sso.v1.UserService/ChangePassword"
	UserService_Get_FullMethodName             = "/sso.v1.UserService/Get"
	UserService_Search_FullMethodName          = "/sso.v1.UserService/Search"
	UserService_ChangeRole_FullMethodName      = "/sso.v1.UserService/ChangeRole"
	UserService_SetStatus_FullMethodName       = "/sso.v1.UserService/SetStatus"
	UserService_CreateModerator_FullMethodName = "/sso.v1.UserService/CreateModerator"
	UserService_DeleteUser_FullMethodName      = "/sso.v1.UserService/DeleteUser"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис управления профилем пользователя.
type UserServiceClient interface {
	// Получение профиля текущего пользователя (по JWT).
	GetProfile(ctx context.Context, in *UserServiceGetProfileRequest, opts ...grpc.CallOption) (*UserServiceGetProfileResponse, error)
	// Обновление профиля текущего пользователя.
	UpdateProfile(ctx context.Context, in *UserServiceUpdateProfileRequest, opts ...grpc.CallOption) (*UserServiceUpdateProfileResponse, error)
	// Смена пароля (требует текущий пароль).
	ChangePassword(ctx context.Context, in *UserServiceChangePasswordRequest, opts ...grpc.CallOption) (*UserServiceChangePasswordResponse, error)
	// Получение профиля другого пользователя по ID.
	// Доступно для модераторов и администраторов.
	Get(ctx context.Context, in *UserServiceGetRequest, opts ...grpc.CallOption) (*UserServiceGetResponse, error)
	// Поиск пользователей по email или display_name.
	// Доступно для модераторов и администраторов.
	Search(ctx context.Context, in *UserServiceSearchRequest, opts ...grpc.CallOption) (*UserServiceSearchResponse, error)
	// Изменение роли пользователя.
	// Доступно только администраторам.
	ChangeRole(ctx context.Context, in *UserServiceChangeRoleRequest, opts ...grpc.CallOption) (*UserServiceChangeRoleResponse, error)
	// Блокировка/разблокировка пользователя.
	// Доступно только администраторам.
	SetStatus(ctx context.Context, in *UserServiceSetStatusRequest, opts ...grpc.CallOption) (*UserServiceSetStatusResponse, error)
	// Создание учётной записи модератора.
	// Доступно только администраторам. Email верификация не требуется.
	CreateModerator(ctx context.Context, in *UserServiceCreateModeratorRequest, opts ...grpc.CallOption) (*UserServiceCreateModeratorResponse, error)
	// Удаление пользователя (hard delete).
	// Доступно только администраторам. Администратор не может удалить другого администратора.
	DeleteUser(ctx context.Context, in *UserServiceDeleteUserRequest, opts ...grpc.CallOption) (*UserServiceDeleteUserResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetProfile(ctx context.Context, in *UserServiceGetProfileRequest, opts ...grpc.CallOption) (*UserServiceGetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserServiceGetProfileResponse)
	err := c.cc.Invoke(ctx, UserService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateProfile(ctx context.Context, in *UserServiceUpdateProfileRequest, opts ...grpc.CallOption) (*UserServiceUpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserServiceUpdateProfileResponse)
	err := c.cc.Invoke(ctx, UserService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ChangePassword(ctx context.Context, in *UserServiceChangePasswordRequest, opts ...grpc.CallOption) (*UserServiceChangePasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserServiceChangePasswordResponse)
	err := c.cc.Invoke(ctx, UserService_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Get(ctx context.Context, in *UserServiceGetRequest, opts ...grpc.CallOption) (*UserServiceGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserServiceGetResponse)
	err := c.cc.Invoke(ctx, UserService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Search(ctx context.Context, in *UserServiceSearchRequest, opts ...grpc.CallOption) (*UserServiceSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserServiceSearchResponse)
	err := c.cc.Invoke(ctx, UserService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ChangeRole(ctx context.Context, in *UserServiceChangeRoleRequest, opts ...grpc.CallOption) (*UserServiceChangeRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserServiceChangeRoleResponse)
	err := c.cc.Invoke(ctx, UserService_ChangeRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SetStatus(ctx context.Context, in *UserServiceSetStatusRequest, opts ...grpc.CallOption) (*UserServiceSetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserServiceSetStatusResponse)
	err := c.cc.Invoke(ctx, UserService_SetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateModerator(ctx context.Context, in *UserServiceCreateModeratorRequest, opts ...grpc.CallOption) (*UserServiceCreateModeratorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserServiceCreateModeratorResponse)
	err := c.cc.Invoke(ctx, UserService_CreateModerator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *UserServiceDeleteUserRequest, opts ...grpc.CallOption) (*UserServiceDeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserServiceDeleteUserResponse)
	err := c.cc.Invoke(ctx, UserService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
//
// Сервис управления профилем пользователя.
type UserServiceServer interface {
	// Получение профиля текущего пользователя (по JWT).
	GetProfile(context.Context, *UserServiceGetProfileRequest) (*UserServiceGetProfileResponse, error)
	// Обновление профиля текущего пользователя.
	UpdateProfile(context.Context, *UserServiceUpdateProfileRequest) (*UserServiceUpdateProfileResponse, error)
	// Смена пароля (требует текущий пароль).
	ChangePassword(context.Context, *UserServiceChangePasswordRequest) (*UserServiceChangePasswordResponse, error)
	// Получение профиля другого пользователя по ID.
	// Доступно для модераторов и администраторов.
	Get(context.Context, *UserServiceGetRequest) (*UserServiceGetResponse, error)
	// Поиск пользователей по email или display_name.
	// Доступно для модераторов и администраторов.
	Search(context.Context, *UserServiceSearchRequest) (*UserServiceSearchResponse, error)
	// Изменение роли пользователя.
	// Доступно только администраторам.
	ChangeRole(context.Context, *UserServiceChangeRoleRequest) (*UserServiceChangeRoleResponse, error)
	// Блокировка/разблокировка пользователя.
	// Доступно только администраторам.
	SetStatus(context.Context, *UserServiceSetStatusRequest) (*UserServiceSetStatusResponse, error)
	// Создание учётной записи модератора.
	// Доступно только администраторам. Email верификация не требуется.
	CreateModerator(context.Context, *UserServiceCreateModeratorRequest) (*UserServiceCreateModeratorResponse, error)
	// Удаление пользователя (hard delete).
	// Доступно только администраторам. Администратор не может удалить другого администратора.
	DeleteUser(context.Context, *UserServiceDeleteUserRequest) (*UserServiceDeleteUserResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) GetProfile(context.Context, *UserServiceGetProfileRequest) (*UserServiceGetProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedUserServiceServer) UpdateProfile(context.Context, *UserServiceUpdateProfileRequest) (*UserServiceUpdateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedUserServiceServer) ChangePassword(context.Context, *UserServiceChangePasswordRequest) (*UserServiceChangePasswordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedUserServiceServer) Get(context.Context, *UserServiceGetRequest) (*UserServiceGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedUserServiceServer) Search(context.Context, *UserServiceSearchRequest) (*UserServiceSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedUserServiceServer) ChangeRole(context.Context, *UserServiceChangeRoleRequest) (*UserServiceChangeRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeRole not implemented")
}
func (UnimplementedUserServiceServer) SetStatus(context.Context, *UserServiceSetStatusRequest) (*UserServiceSetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetStatus not implemented")
}
func (UnimplementedUserServiceServer) CreateModerator(context.Context, *UserServiceCreateModeratorRequest) (*UserServiceCreateModeratorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateModerator not implemented")
}
func (UnimplementedUserServiceServer) DeleteUser(context.Context, *UserServiceDeleteUserRequest) (*UserServiceDeleteUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserServiceGetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetProfile(ctx, req.(*UserServiceGetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserServiceUpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateProfile(ctx, req.(*UserServiceUpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserServiceChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ChangePassword(ctx, req.(*UserServiceChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserServiceGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Get(ctx, req.(*UserServiceGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserServiceSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Search(ctx, req.(*UserServiceSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ChangeRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserServiceChangeRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ChangeRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ChangeRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ChangeRole(ctx, req.(*UserServiceChangeRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserServiceSetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SetStatus(ctx, req.(*UserServiceSetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateModerator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserServiceCreateModeratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateModerator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateModerator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateModerator(ctx, req.(*UserServiceCreateModeratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserServiceDeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*UserServiceDeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sso.v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfile",
			Handler:    _UserService_GetProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _UserService_UpdateProfile_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _UserService_ChangePassword_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _UserService_Get_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _UserService_Search_Handler,
		},
		{
			MethodName: "ChangeRole",
			Handler:    _UserService_ChangeRole_Handler,
		},
		{
			MethodName: "SetStatus",
			Handler:    _UserService_SetStatus_Handler,
		},
		{
			MethodName: "CreateModerator",
			Handler:    _UserService_CreateModerator_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sso/v1/user.proto",
}
