// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: moderation/v1/moderation.proto

package moderationv1

import (
	_ "github.com/Be4Die/game-developer-hub/protos/google/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModerationStatus int32

const (
	ModerationStatus_MODERATION_STATUS_UNSPECIFIED ModerationStatus = 0
	ModerationStatus_MODERATION_STATUS_PENDING     ModerationStatus = 1
	ModerationStatus_MODERATION_STATUS_APPROVED    ModerationStatus = 2
	ModerationStatus_MODERATION_STATUS_REJECTED    ModerationStatus = 3
)

// Enum value maps for ModerationStatus.
var (
	ModerationStatus_name = map[int32]string{
		0: "MODERATION_STATUS_UNSPECIFIED",
		1: "MODERATION_STATUS_PENDING",
		2: "MODERATION_STATUS_APPROVED",
		3: "MODERATION_STATUS_REJECTED",
	}
	ModerationStatus_value = map[string]int32{
		"MODERATION_STATUS_UNSPECIFIED": 0,
		"MODERATION_STATUS_PENDING":     1,
		"MODERATION_STATUS_APPROVED":    2,
		"MODERATION_STATUS_REJECTED":    3,
	}
)

func (x ModerationStatus) Enum() *ModerationStatus {
	p := new(ModerationStatus)
	*p = x
	return p
}

func (x ModerationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModerationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_moderation_v1_moderation_proto_enumTypes[0].Descriptor()
}

func (ModerationStatus) Type() protoreflect.EnumType {
	return &file_moderation_v1_moderation_proto_enumTypes[0]
}

func (x ModerationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModerationStatus.Descriptor instead.
func (ModerationStatus) EnumDescriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{0}
}

type GameModeration struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GameId          int64                  `protobuf:"varint,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	DeveloperId     string                 `protobuf:"bytes,3,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`
	GameName        string                 `protobuf:"bytes,4,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	GameDescription string                 `protobuf:"bytes,5,opt,name=game_description,json=gameDescription,proto3" json:"game_description,omitempty"`
	ModeratorId     string                 `protobuf:"bytes,6,opt,name=moderator_id,json=moderatorId,proto3" json:"moderator_id,omitempty"`
	Status          ModerationStatus       `protobuf:"varint,7,opt,name=status,proto3,enum=moderation.v1.ModerationStatus" json:"status,omitempty"`
	RejectionReason string                 `protobuf:"bytes,8,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	SubmittedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	ReviewedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=reviewed_at,json=reviewedAt,proto3" json:"reviewed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GameModeration) Reset() {
	*x = GameModeration{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameModeration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameModeration) ProtoMessage() {}

func (x *GameModeration) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameModeration.ProtoReflect.Descriptor instead.
func (*GameModeration) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{0}
}

func (x *GameModeration) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameModeration) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GameModeration) GetDeveloperId() string {
	if x != nil {
		return x.DeveloperId
	}
	return ""
}

func (x *GameModeration) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *GameModeration) GetGameDescription() string {
	if x != nil {
		return x.GameDescription
	}
	return ""
}

func (x *GameModeration) GetModeratorId() string {
	if x != nil {
		return x.ModeratorId
	}
	return ""
}

func (x *GameModeration) GetStatus() ModerationStatus {
	if x != nil {
		return x.Status
	}
	return ModerationStatus_MODERATION_STATUS_UNSPECIFIED
}

func (x *GameModeration) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *GameModeration) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

func (x *GameModeration) GetReviewedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReviewedAt
	}
	return nil
}

type SubmitForReviewRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GameId          int64                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	GameName        string                 `protobuf:"bytes,2,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	GameDescription string                 `protobuf:"bytes,3,opt,name=game_description,json=gameDescription,proto3" json:"game_description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitForReviewRequest) Reset() {
	*x = SubmitForReviewRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitForReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitForReviewRequest) ProtoMessage() {}

func (x *SubmitForReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitForReviewRequest.ProtoReflect.Descriptor instead.
func (*SubmitForReviewRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitForReviewRequest) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *SubmitForReviewRequest) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *SubmitForReviewRequest) GetGameDescription() string {
	if x != nil {
		return x.GameDescription
	}
	return ""
}

type SubmitForReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moderation    *GameModeration        `protobuf:"bytes,1,opt,name=moderation,proto3" json:"moderation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitForReviewResponse) Reset() {
	*x = SubmitForReviewResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitForReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitForReviewResponse) ProtoMessage() {}

func (x *SubmitForReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitForReviewResponse.ProtoReflect.Descriptor instead.
func (*SubmitForReviewResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitForReviewResponse) GetModeration() *GameModeration {
	if x != nil {
		return x.Moderation
	}
	return nil
}

type GetModerationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int64                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModerationStatusRequest) Reset() {
	*x = GetModerationStatusRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModerationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModerationStatusRequest) ProtoMessage() {}

func (x *GetModerationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModerationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetModerationStatusRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{3}
}

func (x *GetModerationStatusRequest) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type GetModerationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moderation    *GameModeration        `protobuf:"bytes,1,opt,name=moderation,proto3" json:"moderation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModerationStatusResponse) Reset() {
	*x = GetModerationStatusResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModerationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModerationStatusResponse) ProtoMessage() {}

func (x *GetModerationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModerationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetModerationStatusResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{4}
}

func (x *GetModerationStatusResponse) GetModeration() *GameModeration {
	if x != nil {
		return x.Moderation
	}
	return nil
}

type ListPendingGamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingGamesRequest) Reset() {
	*x = ListPendingGamesRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingGamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingGamesRequest) ProtoMessage() {}

func (x *ListPendingGamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingGamesRequest.ProtoReflect.Descriptor instead.
func (*ListPendingGamesRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{5}
}

func (x *ListPendingGamesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPendingGamesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListPendingGamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moderations   []*GameModeration      `protobuf:"bytes,1,rep,name=moderations,proto3" json:"moderations,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingGamesResponse) Reset() {
	*x = ListPendingGamesResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingGamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingGamesResponse) ProtoMessage() {}

func (x *ListPendingGamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingGamesResponse.ProtoReflect.Descriptor instead.
func (*ListPendingGamesResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{6}
}

func (x *ListPendingGamesResponse) GetModerations() []*GameModeration {
	if x != nil {
		return x.Moderations
	}
	return nil
}

func (x *ListPendingGamesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ApproveGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int64                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveGameRequest) Reset() {
	*x = ApproveGameRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveGameRequest) ProtoMessage() {}

func (x *ApproveGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveGameRequest.ProtoReflect.Descriptor instead.
func (*ApproveGameRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{7}
}

func (x *ApproveGameRequest) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type ApproveGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moderation    *GameModeration        `protobuf:"bytes,1,opt,name=moderation,proto3" json:"moderation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveGameResponse) Reset() {
	*x = ApproveGameResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveGameResponse) ProtoMessage() {}

func (x *ApproveGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveGameResponse.ProtoReflect.Descriptor instead.
func (*ApproveGameResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{8}
}

func (x *ApproveGameResponse) GetModeration() *GameModeration {
	if x != nil {
		return x.Moderation
	}
	return nil
}

type RejectGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int64                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectGameRequest) Reset() {
	*x = RejectGameRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectGameRequest) ProtoMessage() {}

func (x *RejectGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectGameRequest.ProtoReflect.Descriptor instead.
func (*RejectGameRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{9}
}

func (x *RejectGameRequest) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *RejectGameRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RejectGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moderation    *GameModeration        `protobuf:"bytes,1,opt,name=moderation,proto3" json:"moderation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectGameResponse) Reset() {
	*x = RejectGameResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectGameResponse) ProtoMessage() {}

func (x *RejectGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectGameResponse.ProtoReflect.Descriptor instead.
func (*RejectGameResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{10}
}

func (x *RejectGameResponse) GetModeration() *GameModeration {
	if x != nil {
		return x.Moderation
	}
	return nil
}

var File_moderation_v1_moderation_proto protoreflect.FileDescriptor

const file_moderation_v1_moderation_proto_rawDesc = "" +
	"\n" +
	"\x1emoderation/v1/moderation.proto\x12\rmoderation.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa7\x03\n" +
	"\x0eGameModeration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\x03R\x06gameId\x12!\n" +
	"\fdeveloper_id\x18\x03 \x01(\tR\vdeveloperId\x12\x1b\n" +
	"\tgame_name\x18\x04 \x01(\tR\bgameName\x12)\n" +
	"\x10game_description\x18\x05 \x01(\tR\x0fgameDescription\x12!\n" +
	"\fmoderator_id\x18\x06 \x01(\tR\vmoderatorId\x127\n" +
	"\x06status\x18\a \x01(\x0e2\x1f.moderation.v1.ModerationStatusR\x06status\x12)\n" +
	"\x10rejection_reason\x18\b \x01(\tR\x0frejectionReason\x12=\n" +
	"\fsubmitted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\x12;\n" +
	"\vreviewed_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reviewedAt\"y\n" +
	"\x16SubmitForReviewRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x03R\x06gameId\x12\x1b\n" +
	"\tgame_name\x18\x02 \x01(\tR\bgameName\x12)\n" +
	"\x10game_description\x18\x03 \x01(\tR\x0fgameDescription\"X\n" +
	"\x17SubmitForReviewResponse\x12=\n" +
	"\n" +
	"moderation\x18\x01 \x01(\v2\x1d.moderation.v1.GameModerationR\n" +
	"moderation\"5\n" +
	"\x1aGetModerationStatusRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x03R\x06gameId\"\\\n" +
	"\x1bGetModerationStatusResponse\x12=\n" +
	"\n" +
	"moderation\x18\x01 \x01(\v2\x1d.moderation.v1.GameModerationR\n" +
	"moderation\"G\n" +
	"\x17ListPendingGamesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"|\n" +
	"\x18ListPendingGamesResponse\x12?\n" +
	"\vmoderations\x18\x01 \x03(\v2\x1d.moderation.v1.GameModerationR\vmoderations\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"-\n" +
	"\x12ApproveGameRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x03R\x06gameId\"T\n" +
	"\x13ApproveGameResponse\x12=\n" +
	"\n" +
	"moderation\x18\x01 \x01(\v2\x1d.moderation.v1.GameModerationR\n" +
	"moderation\"D\n" +
	"\x11RejectGameRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x03R\x06gameId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"S\n" +
	"\x12RejectGameResponse\x12=\n" +
	"\n" +
	"moderation\x18\x01 \x01(\v2\x1d.moderation.v1.GameModerationR\n" +
	"moderation*\x94\x01\n" +
	"\x10ModerationStatus\x12!\n" +
	"\x1dMODERATION_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19MODERATION_STATUS_PENDING\x10\x01\x12\x1e\n" +
	"\x1aMODERATION_STATUS_APPROVED\x10\x02\x12\x1e\n" +
	"\x1aMODERATION_STATUS_REJECTED\x10\x032\xf0\x05\n" +
	"\x11ModerationService\x12\x96\x01\n" +
	"\x0fSubmitForReview\x12%.moderation.v1.SubmitForReviewRequest\x1a&.moderation.v1.SubmitForReviewResponse\"4\x82\xd3\xe4\x93\x02.:\x01*\")/api/v1/moderation/games/{game_id}/submit\x12\x9f\x01\n" +
	"\x13GetModerationStatus\x12).moderation.v1.GetModerationStatusRequest\x1a*.moderation.v1.GetModerationStatusResponse\"1\x82\xd3\xe4\x93\x02+\x12)/api/v1/moderation/games/{game_id}/status\x12\x87\x01\n" +
	"\x10ListPendingGames\x12&.moderation.v1.ListPendingGamesRequest\x1a'.moderation.v1.ListPendingGamesResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/moderation/pending\x12\x8b\x01\n" +
	"\vApproveGame\x12!.moderation.v1.ApproveGameRequest\x1a\".moderation.v1.ApproveGameResponse\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/api/v1/moderation/games/{game_id}/approve\x12\x87\x01\n" +
	"\n" +
	"RejectGame\x12 .moderation.v1.RejectGameRequest\x1a!.moderation.v1.RejectGameResponse\"4\x82\xd3\xe4\x93\x02.:\x01*\")/api/v1/moderation/games/{game_id}/rejectB\xc1\x01\n" +
	"\x11com.moderation.v1B\x0fModerationProtoP\x01ZFgithub.com/Be4Die/game-developer-hub/protos/moderation/v1;moderationv1\xa2\x02\x03MXX\xaa\x02\rModeration.V1\xca\x02\rModeration\\V1\xe2\x02\x19Moderation\\V1\\GPBMetadata\xea\x02\x0eModeration::V1b\x06proto3"

var (
	file_moderation_v1_moderation_proto_rawDescOnce sync.Once
	file_moderation_v1_moderation_proto_rawDescData []byte
)

func file_moderation_v1_moderation_proto_rawDescGZIP() []byte {
	file_moderation_v1_moderation_proto_rawDescOnce.Do(func() {
		file_moderation_v1_moderation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moderation_v1_moderation_proto_rawDesc), len(file_moderation_v1_moderation_proto_rawDesc)))
	})
	return file_moderation_v1_moderation_proto_rawDescData
}

var file_moderation_v1_moderation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_moderation_v1_moderation_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_moderation_v1_moderation_proto_goTypes = []any{
	(ModerationStatus)(0),               // 0: moderation.v1.ModerationStatus
	(*GameModeration)(nil),              // 1: moderation.v1.GameModeration
	(*SubmitForReviewRequest)(nil),      // 2: moderation.v1.SubmitForReviewRequest
	(*SubmitForReviewResponse)(nil),     // 3: moderation.v1.SubmitForReviewResponse
	(*GetModerationStatusRequest)(nil),  // 4: moderation.v1.GetModerationStatusRequest
	(*GetModerationStatusResponse)(nil), // 5: moderation.v1.GetModerationStatusResponse
	(*ListPendingGamesRequest)(nil),     // 6: moderation.v1.ListPendingGamesRequest
	(*ListPendingGamesResponse)(nil),    // 7: moderation.v1.ListPendingGamesResponse
	(*ApproveGameRequest)(nil),          // 8: moderation.v1.ApproveGameRequest
	(*ApproveGameResponse)(nil),         // 9: moderation.v1.ApproveGameResponse
	(*RejectGameRequest)(nil),           // 10: moderation.v1.RejectGameRequest
	(*RejectGameResponse)(nil),          // 11: moderation.v1.RejectGameResponse
	(*timestamppb.Timestamp)(nil),       // 12: google.protobuf.Timestamp
}
var file_moderation_v1_moderation_proto_depIdxs = []int32{
	0,  // 0: moderation.v1.GameModeration.status:type_name -> moderation.v1.ModerationStatus
	12, // 1: moderation.v1.GameModeration.submitted_at:type_name -> google.protobuf.Timestamp
	12, // 2: moderation.v1.GameModeration.reviewed_at:type_name -> google.protobuf.Timestamp
	1,  // 3: moderation.v1.SubmitForReviewResponse.moderation:type_name -> moderation.v1.GameModeration
	1,  // 4: moderation.v1.GetModerationStatusResponse.moderation:type_name -> moderation.v1.GameModeration
	1,  // 5: moderation.v1.ListPendingGamesResponse.moderations:type_name -> moderation.v1.GameModeration
	1,  // 6: moderation.v1.ApproveGameResponse.moderation:type_name -> moderation.v1.GameModeration
	1,  // 7: moderation.v1.RejectGameResponse.moderation:type_name -> moderation.v1.GameModeration
	2,  // 8: moderation.v1.ModerationService.SubmitForReview:input_type -> moderation.v1.SubmitForReviewRequest
	4,  // 9: moderation.v1.ModerationService.GetModerationStatus:input_type -> moderation.v1.GetModerationStatusRequest
	6,  // 10: moderation.v1.ModerationService.ListPendingGames:input_type -> moderation.v1.ListPendingGamesRequest
	8,  // 11: moderation.v1.ModerationService.ApproveGame:input_type -> moderation.v1.ApproveGameRequest
	10, // 12: moderation.v1.ModerationService.RejectGame:input_type -> moderation.v1.RejectGameRequest
	3,  // 13: moderation.v1.ModerationService.SubmitForReview:output_type -> moderation.v1.SubmitForReviewResponse
	5,  // 14: moderation.v1.ModerationService.GetModerationStatus:output_type -> moderation.v1.GetModerationStatusResponse
	7,  // 15: moderation.v1.ModerationService.ListPendingGames:output_type -> moderation.v1.ListPendingGamesResponse
	9,  // 16: moderation.v1.ModerationService.ApproveGame:output_type -> moderation.v1.ApproveGameResponse
	11, // 17: moderation.v1.ModerationService.RejectGame:output_type -> moderation.v1.RejectGameResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_moderation_v1_moderation_proto_init() }
func file_moderation_v1_moderation_proto_init() {
	if File_moderation_v1_moderation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moderation_v1_moderation_proto_rawDesc), len(file_moderation_v1_moderation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moderation_v1_moderation_proto_goTypes,
		DependencyIndexes: file_moderation_v1_moderation_proto_depIdxs,
		EnumInfos:         file_moderation_v1_moderation_proto_enumTypes,
		MessageInfos:      file_moderation_v1_moderation_proto_msgTypes,
	}.Build()
	File_moderation_v1_moderation_proto = out.File
	file_moderation_v1_moderation_proto_goTypes = nil
	file_moderation_v1_moderation_proto_depIdxs = nil
}
