// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: moderation/v1/moderation.proto

package moderationv1

import (
	_ "github.com/Be4Die/game-developer-hub/protos/google/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RequestStatus статус рассмотрения заявки модератором.
type RequestStatus int32

const (
	RequestStatus_REQUEST_STATUS_UNSPECIFIED RequestStatus = 0
	RequestStatus_REQUEST_STATUS_PENDING     RequestStatus = 1
	RequestStatus_REQUEST_STATUS_IN_REVIEW   RequestStatus = 2
	RequestStatus_REQUEST_STATUS_APPROVED    RequestStatus = 3
	RequestStatus_REQUEST_STATUS_REJECTED    RequestStatus = 4
	RequestStatus_REQUEST_STATUS_CANCELLED   RequestStatus = 5
)

// Enum value maps for RequestStatus.
var (
	RequestStatus_name = map[int32]string{
		0: "REQUEST_STATUS_UNSPECIFIED",
		1: "REQUEST_STATUS_PENDING",
		2: "REQUEST_STATUS_IN_REVIEW",
		3: "REQUEST_STATUS_APPROVED",
		4: "REQUEST_STATUS_REJECTED",
		5: "REQUEST_STATUS_CANCELLED",
	}
	RequestStatus_value = map[string]int32{
		"REQUEST_STATUS_UNSPECIFIED": 0,
		"REQUEST_STATUS_PENDING":     1,
		"REQUEST_STATUS_IN_REVIEW":   2,
		"REQUEST_STATUS_APPROVED":    3,
		"REQUEST_STATUS_REJECTED":    4,
		"REQUEST_STATUS_CANCELLED":   5,
	}
)

func (x RequestStatus) Enum() *RequestStatus {
	p := new(RequestStatus)
	*p = x
	return p
}

func (x RequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_moderation_v1_moderation_proto_enumTypes[0].Descriptor()
}

func (RequestStatus) Type() protoreflect.EnumType {
	return &file_moderation_v1_moderation_proto_enumTypes[0]
}

func (x RequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestStatus.Descriptor instead.
func (RequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{0}
}

// SenderRole роль отправителя сообщения в чате проекта.
type SenderRole int32

const (
	SenderRole_SENDER_ROLE_UNSPECIFIED SenderRole = 0
	SenderRole_SENDER_ROLE_DEVELOPER   SenderRole = 1
	SenderRole_SENDER_ROLE_MODERATOR   SenderRole = 2
	SenderRole_SENDER_ROLE_SYSTEM      SenderRole = 3
)

// Enum value maps for SenderRole.
var (
	SenderRole_name = map[int32]string{
		0: "SENDER_ROLE_UNSPECIFIED",
		1: "SENDER_ROLE_DEVELOPER",
		2: "SENDER_ROLE_MODERATOR",
		3: "SENDER_ROLE_SYSTEM",
	}
	SenderRole_value = map[string]int32{
		"SENDER_ROLE_UNSPECIFIED": 0,
		"SENDER_ROLE_DEVELOPER":   1,
		"SENDER_ROLE_MODERATOR":   2,
		"SENDER_ROLE_SYSTEM":      3,
	}
)

func (x SenderRole) Enum() *SenderRole {
	p := new(SenderRole)
	*p = x
	return p
}

func (x SenderRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SenderRole) Descriptor() protoreflect.EnumDescriptor {
	return file_moderation_v1_moderation_proto_enumTypes[1].Descriptor()
}

func (SenderRole) Type() protoreflect.EnumType {
	return &file_moderation_v1_moderation_proto_enumTypes[1]
}

func (x SenderRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SenderRole.Descriptor instead.
func (SenderRole) EnumDescriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{1}
}

// MessageType тип сообщения в чате проекта.
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED    MessageType = 0
	MessageType_MESSAGE_TYPE_TEXT           MessageType = 1
	MessageType_MESSAGE_TYPE_SUBMITTED      MessageType = 2
	MessageType_MESSAGE_TYPE_STATUS_CHANGED MessageType = 3
	MessageType_MESSAGE_TYPE_APPROVED       MessageType = 4
	MessageType_MESSAGE_TYPE_REJECTED       MessageType = 5
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_TEXT",
		2: "MESSAGE_TYPE_SUBMITTED",
		3: "MESSAGE_TYPE_STATUS_CHANGED",
		4: "MESSAGE_TYPE_APPROVED",
		5: "MESSAGE_TYPE_REJECTED",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":    0,
		"MESSAGE_TYPE_TEXT":           1,
		"MESSAGE_TYPE_SUBMITTED":      2,
		"MESSAGE_TYPE_STATUS_CHANGED": 3,
		"MESSAGE_TYPE_APPROVED":       4,
		"MESSAGE_TYPE_REJECTED":       5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_moderation_v1_moderation_proto_enumTypes[2].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_moderation_v1_moderation_proto_enumTypes[2]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{2}
}

// ProjectSnapshot снимок состояния черновика на момент отправки на модерацию.
type ProjectSnapshot struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProjectId          int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TitleRu            string                 `protobuf:"bytes,2,opt,name=title_ru,json=titleRu,proto3" json:"title_ru,omitempty"`
	TitleEn            string                 `protobuf:"bytes,3,opt,name=title_en,json=titleEn,proto3" json:"title_en,omitempty"`
	SeoRu              string                 `protobuf:"bytes,4,opt,name=seo_ru,json=seoRu,proto3" json:"seo_ru,omitempty"`
	SeoEn              string                 `protobuf:"bytes,5,opt,name=seo_en,json=seoEn,proto3" json:"seo_en,omitempty"`
	About              string                 `protobuf:"bytes,6,opt,name=about,proto3" json:"about,omitempty"`
	IconPath           string                 `protobuf:"bytes,7,opt,name=icon_path,json=iconPath,proto3" json:"icon_path,omitempty"`
	CoverPath          string                 `protobuf:"bytes,8,opt,name=cover_path,json=coverPath,proto3" json:"cover_path,omitempty"`
	VideoPath          string                 `protobuf:"bytes,9,opt,name=video_path,json=videoPath,proto3" json:"video_path,omitempty"`
	ActiveBuildVersion string                 `protobuf:"bytes,10,opt,name=active_build_version,json=activeBuildVersion,proto3" json:"active_build_version,omitempty"`
	DevUrl             string                 `protobuf:"bytes,11,opt,name=dev_url,json=devUrl,proto3" json:"dev_url,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProjectSnapshot) Reset() {
	*x = ProjectSnapshot{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSnapshot) ProtoMessage() {}

func (x *ProjectSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSnapshot.ProtoReflect.Descriptor instead.
func (*ProjectSnapshot) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectSnapshot) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ProjectSnapshot) GetTitleRu() string {
	if x != nil {
		return x.TitleRu
	}
	return ""
}

func (x *ProjectSnapshot) GetTitleEn() string {
	if x != nil {
		return x.TitleEn
	}
	return ""
}

func (x *ProjectSnapshot) GetSeoRu() string {
	if x != nil {
		return x.SeoRu
	}
	return ""
}

func (x *ProjectSnapshot) GetSeoEn() string {
	if x != nil {
		return x.SeoEn
	}
	return ""
}

func (x *ProjectSnapshot) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

func (x *ProjectSnapshot) GetIconPath() string {
	if x != nil {
		return x.IconPath
	}
	return ""
}

func (x *ProjectSnapshot) GetCoverPath() string {
	if x != nil {
		return x.CoverPath
	}
	return ""
}

func (x *ProjectSnapshot) GetVideoPath() string {
	if x != nil {
		return x.VideoPath
	}
	return ""
}

func (x *ProjectSnapshot) GetActiveBuildVersion() string {
	if x != nil {
		return x.ActiveBuildVersion
	}
	return ""
}

func (x *ProjectSnapshot) GetDevUrl() string {
	if x != nil {
		return x.DevUrl
	}
	return ""
}

// ModerationRequest сущность запроса на модерацию проекта.
type ModerationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId       int64                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	OwnerId         string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ModeratorId     string                 `protobuf:"bytes,4,opt,name=moderator_id,json=moderatorId,proto3" json:"moderator_id,omitempty"`
	Status          RequestStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=moderation.v1.RequestStatus" json:"status,omitempty"`
	Snapshot        *ProjectSnapshot       `protobuf:"bytes,6,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	RejectionReason string                 `protobuf:"bytes,7,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	SubmittedAt     string                 `protobuf:"bytes,8,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	StartedReviewAt string                 `protobuf:"bytes,9,opt,name=started_review_at,json=startedReviewAt,proto3" json:"started_review_at,omitempty"`
	ResolvedAt      string                 `protobuf:"bytes,10,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ModerationRequest) Reset() {
	*x = ModerationRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModerationRequest) ProtoMessage() {}

func (x *ModerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModerationRequest.ProtoReflect.Descriptor instead.
func (*ModerationRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{1}
}

func (x *ModerationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModerationRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ModerationRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ModerationRequest) GetModeratorId() string {
	if x != nil {
		return x.ModeratorId
	}
	return ""
}

func (x *ModerationRequest) GetStatus() RequestStatus {
	if x != nil {
		return x.Status
	}
	return RequestStatus_REQUEST_STATUS_UNSPECIFIED
}

func (x *ModerationRequest) GetSnapshot() *ProjectSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *ModerationRequest) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *ModerationRequest) GetSubmittedAt() string {
	if x != nil {
		return x.SubmittedAt
	}
	return ""
}

func (x *ModerationRequest) GetStartedReviewAt() string {
	if x != nil {
		return x.StartedReviewAt
	}
	return ""
}

func (x *ModerationRequest) GetResolvedAt() string {
	if x != nil {
		return x.ResolvedAt
	}
	return ""
}

// ChatMessage сообщение или системное событие в чате проекта.
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     int64                  `protobuf:"varint,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	RequestId     int64                  `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderRole    SenderRole             `protobuf:"varint,5,opt,name=sender_role,json=senderRole,proto3,enum=moderation.v1.SenderRole" json:"sender_role,omitempty"`
	MessageType   MessageType            `protobuf:"varint,6,opt,name=message_type,json=messageType,proto3,enum=moderation.v1.MessageType" json:"message_type,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChatMessage) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ChatMessage) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ChatMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChatMessage) GetSenderRole() SenderRole {
	if x != nil {
		return x.SenderRole
	}
	return SenderRole_SENDER_ROLE_UNSPECIFIED
}

func (x *ChatMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SubmitDraftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Snapshot      *ProjectSnapshot       `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDraftRequest) Reset() {
	*x = SubmitDraftRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDraftRequest) ProtoMessage() {}

func (x *SubmitDraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDraftRequest.ProtoReflect.Descriptor instead.
func (*SubmitDraftRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitDraftRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *SubmitDraftRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *SubmitDraftRequest) GetSnapshot() *ProjectSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type SubmitDraftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Request       *ModerationRequest     `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitDraftResponse) Reset() {
	*x = SubmitDraftResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitDraftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDraftResponse) ProtoMessage() {}

func (x *SubmitDraftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDraftResponse.ProtoReflect.Descriptor instead.
func (*SubmitDraftResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitDraftResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitDraftResponse) GetRequest() *ModerationRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type ListModerationRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        RequestStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=moderation.v1.RequestStatus" json:"status,omitempty"`
	ModeratorId   string                 `protobuf:"bytes,2,opt,name=moderator_id,json=moderatorId,proto3" json:"moderator_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModerationRequestsRequest) Reset() {
	*x = ListModerationRequestsRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModerationRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModerationRequestsRequest) ProtoMessage() {}

func (x *ListModerationRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModerationRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListModerationRequestsRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{5}
}

func (x *ListModerationRequestsRequest) GetStatus() RequestStatus {
	if x != nil {
		return x.Status
	}
	return RequestStatus_REQUEST_STATUS_UNSPECIFIED
}

func (x *ListModerationRequestsRequest) GetModeratorId() string {
	if x != nil {
		return x.ModeratorId
	}
	return ""
}

func (x *ListModerationRequestsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListModerationRequestsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListModerationRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*ModerationRequest   `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModerationRequestsResponse) Reset() {
	*x = ListModerationRequestsResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModerationRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModerationRequestsResponse) ProtoMessage() {}

func (x *ListModerationRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModerationRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListModerationRequestsResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{6}
}

func (x *ListModerationRequestsResponse) GetRequests() []*ModerationRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *ListModerationRequestsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetModerationRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModerationRequestRequest) Reset() {
	*x = GetModerationRequestRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModerationRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModerationRequestRequest) ProtoMessage() {}

func (x *GetModerationRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModerationRequestRequest.ProtoReflect.Descriptor instead.
func (*GetModerationRequestRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{7}
}

func (x *GetModerationRequestRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type GetModerationRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *ModerationRequest     `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModerationRequestResponse) Reset() {
	*x = GetModerationRequestResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModerationRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModerationRequestResponse) ProtoMessage() {}

func (x *GetModerationRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModerationRequestResponse.ProtoReflect.Descriptor instead.
func (*GetModerationRequestResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{8}
}

func (x *GetModerationRequestResponse) GetRequest() *ModerationRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type GetLatestRequestByProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestRequestByProjectRequest) Reset() {
	*x = GetLatestRequestByProjectRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestRequestByProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestRequestByProjectRequest) ProtoMessage() {}

func (x *GetLatestRequestByProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestRequestByProjectRequest.ProtoReflect.Descriptor instead.
func (*GetLatestRequestByProjectRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{9}
}

func (x *GetLatestRequestByProjectRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type ClaimModerationRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimModerationRequestRequest) Reset() {
	*x = ClaimModerationRequestRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimModerationRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimModerationRequestRequest) ProtoMessage() {}

func (x *ClaimModerationRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimModerationRequestRequest.ProtoReflect.Descriptor instead.
func (*ClaimModerationRequestRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{10}
}

func (x *ClaimModerationRequestRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type ClaimModerationRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *ModerationRequest     `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimModerationRequestResponse) Reset() {
	*x = ClaimModerationRequestResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimModerationRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimModerationRequestResponse) ProtoMessage() {}

func (x *ClaimModerationRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimModerationRequestResponse.ProtoReflect.Descriptor instead.
func (*ClaimModerationRequestResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{11}
}

func (x *ClaimModerationRequestResponse) GetRequest() *ModerationRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type ApproveModerationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveModerationRequest) Reset() {
	*x = ApproveModerationRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveModerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveModerationRequest) ProtoMessage() {}

func (x *ApproveModerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveModerationRequest.ProtoReflect.Descriptor instead.
func (*ApproveModerationRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{12}
}

func (x *ApproveModerationRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ApproveModerationRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type ApproveModerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Request       *ModerationRequest     `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	ProdUrl       string                 `protobuf:"bytes,3,opt,name=prod_url,json=prodUrl,proto3" json:"prod_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveModerationResponse) Reset() {
	*x = ApproveModerationResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveModerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveModerationResponse) ProtoMessage() {}

func (x *ApproveModerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveModerationResponse.ProtoReflect.Descriptor instead.
func (*ApproveModerationResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{13}
}

func (x *ApproveModerationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApproveModerationResponse) GetRequest() *ModerationRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ApproveModerationResponse) GetProdUrl() string {
	if x != nil {
		return x.ProdUrl
	}
	return ""
}

type RejectModerationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectModerationRequest) Reset() {
	*x = RejectModerationRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectModerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectModerationRequest) ProtoMessage() {}

func (x *RejectModerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectModerationRequest.ProtoReflect.Descriptor instead.
func (*RejectModerationRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{14}
}

func (x *RejectModerationRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *RejectModerationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RejectModerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Request       *ModerationRequest     `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectModerationResponse) Reset() {
	*x = RejectModerationResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectModerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectModerationResponse) ProtoMessage() {}

func (x *RejectModerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectModerationResponse.ProtoReflect.Descriptor instead.
func (*RejectModerationResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{15}
}

func (x *RejectModerationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RejectModerationResponse) GetRequest() *ModerationRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type SendChatMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChatMessageRequest) Reset() {
	*x = SendChatMessageRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatMessageRequest) ProtoMessage() {}

func (x *SendChatMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatMessageRequest.ProtoReflect.Descriptor instead.
func (*SendChatMessageRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{16}
}

func (x *SendChatMessageRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *SendChatMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendChatMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ChatMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChatMessageResponse) Reset() {
	*x = SendChatMessageResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChatMessageResponse) ProtoMessage() {}

func (x *SendChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChatMessageResponse.ProtoReflect.Descriptor instead.
func (*SendChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{17}
}

func (x *SendChatMessageResponse) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type ListChatMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatMessagesRequest) Reset() {
	*x = ListChatMessagesRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatMessagesRequest) ProtoMessage() {}

func (x *ListChatMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListChatMessagesRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{18}
}

func (x *ListChatMessagesRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ListChatMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListChatMessagesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListChatMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatMessagesResponse) Reset() {
	*x = ListChatMessagesResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatMessagesResponse) ProtoMessage() {}

func (x *ListChatMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListChatMessagesResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{19}
}

func (x *ListChatMessagesResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListChatMessagesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ChatSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	LastMessage   *ChatMessage           `protobuf:"bytes,2,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatSummary) Reset() {
	*x = ChatSummary{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSummary) ProtoMessage() {}

func (x *ChatSummary) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSummary.ProtoReflect.Descriptor instead.
func (*ChatSummary) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{20}
}

func (x *ChatSummary) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ChatSummary) GetLastMessage() *ChatMessage {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

type ListActiveChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveChatsRequest) Reset() {
	*x = ListActiveChatsRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveChatsRequest) ProtoMessage() {}

func (x *ListActiveChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveChatsRequest.ProtoReflect.Descriptor instead.
func (*ListActiveChatsRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{21}
}

func (x *ListActiveChatsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListActiveChatsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListActiveChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*ChatSummary         `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveChatsResponse) Reset() {
	*x = ListActiveChatsResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveChatsResponse) ProtoMessage() {}

func (x *ListActiveChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveChatsResponse.ProtoReflect.Descriptor instead.
func (*ListActiveChatsResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{22}
}

func (x *ListActiveChatsResponse) GetChats() []*ChatSummary {
	if x != nil {
		return x.Chats
	}
	return nil
}

func (x *ListActiveChatsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_moderation_v1_moderation_proto protoreflect.FileDescriptor

const file_moderation_v1_moderation_proto_rawDesc = "" +
	"\n" +
	"\x1emoderation/v1/moderation.proto\x12\rmoderation.v1\x1a\x1cgoogle/api/annotations.proto\"\xd0\x02\n" +
	"\x0fProjectSnapshot\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12\x19\n" +
	"\btitle_ru\x18\x02 \x01(\tR\atitleRu\x12\x19\n" +
	"\btitle_en\x18\x03 \x01(\tR\atitleEn\x12\x15\n" +
	"\x06seo_ru\x18\x04 \x01(\tR\x05seoRu\x12\x15\n" +
	"\x06seo_en\x18\x05 \x01(\tR\x05seoEn\x12\x14\n" +
	"\x05about\x18\x06 \x01(\tR\x05about\x12\x1b\n" +
	"\ticon_path\x18\a \x01(\tR\biconPath\x12\x1d\n" +
	"\n" +
	"cover_path\x18\b \x01(\tR\tcoverPath\x12\x1d\n" +
	"\n" +
	"video_path\x18\t \x01(\tR\tvideoPath\x120\n" +
	"\x14active_build_version\x18\n" +
	" \x01(\tR\x12activeBuildVersion\x12\x17\n" +
	"\adev_url\x18\v \x01(\tR\x06devUrl\"\x8d\x03\n" +
	"\x11ModerationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x03R\tprojectId\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12!\n" +
	"\fmoderator_id\x18\x04 \x01(\tR\vmoderatorId\x124\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1c.moderation.v1.RequestStatusR\x06status\x12:\n" +
	"\bsnapshot\x18\x06 \x01(\v2\x1e.moderation.v1.ProjectSnapshotR\bsnapshot\x12)\n" +
	"\x10rejection_reason\x18\a \x01(\tR\x0frejectionReason\x12!\n" +
	"\fsubmitted_at\x18\b \x01(\tR\vsubmittedAt\x12*\n" +
	"\x11started_review_at\x18\t \x01(\tR\x0fstartedReviewAt\x12\x1f\n" +
	"\vresolved_at\x18\n" +
	" \x01(\tR\n" +
	"resolvedAt\"\xac\x02\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\x03R\tprojectId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\x03R\trequestId\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\tR\bsenderId\x12:\n" +
	"\vsender_role\x18\x05 \x01(\x0e2\x19.moderation.v1.SenderRoleR\n" +
	"senderRole\x12=\n" +
	"\fmessage_type\x18\x06 \x01(\x0e2\x1a.moderation.v1.MessageTypeR\vmessageType\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\x8a\x01\n" +
	"\x12SubmitDraftRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12:\n" +
	"\bsnapshot\x18\x03 \x01(\v2\x1e.moderation.v1.ProjectSnapshotR\bsnapshot\"k\n" +
	"\x13SubmitDraftResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12:\n" +
	"\arequest\x18\x02 \x01(\v2 .moderation.v1.ModerationRequestR\arequest\"\xa6\x01\n" +
	"\x1dListModerationRequestsRequest\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.moderation.v1.RequestStatusR\x06status\x12!\n" +
	"\fmoderator_id\x18\x02 \x01(\tR\vmoderatorId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"t\n" +
	"\x1eListModerationRequestsResponse\x12<\n" +
	"\brequests\x18\x01 \x03(\v2 .moderation.v1.ModerationRequestR\brequests\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"<\n" +
	"\x1bGetModerationRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\"Z\n" +
	"\x1cGetModerationRequestResponse\x12:\n" +
	"\arequest\x18\x01 \x01(\v2 .moderation.v1.ModerationRequestR\arequest\"A\n" +
	" GetLatestRequestByProjectRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\">\n" +
	"\x1dClaimModerationRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\"\\\n" +
	"\x1eClaimModerationRequestResponse\x12:\n" +
	"\arequest\x18\x01 \x01(\v2 .moderation.v1.ModerationRequestR\arequest\"S\n" +
	"\x18ApproveModerationRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\"\x8c\x01\n" +
	"\x19ApproveModerationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12:\n" +
	"\arequest\x18\x02 \x01(\v2 .moderation.v1.ModerationRequestR\arequest\x12\x19\n" +
	"\bprod_url\x18\x03 \x01(\tR\aprodUrl\"P\n" +
	"\x17RejectModerationRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"p\n" +
	"\x18RejectModerationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12:\n" +
	"\arequest\x18\x02 \x01(\v2 .moderation.v1.ModerationRequestR\arequest\"Q\n" +
	"\x16SendChatMessageRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"O\n" +
	"\x17SendChatMessageResponse\x124\n" +
	"\amessage\x18\x01 \x01(\v2\x1a.moderation.v1.ChatMessageR\amessage\"f\n" +
	"\x17ListChatMessagesRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"h\n" +
	"\x18ListChatMessagesResponse\x126\n" +
	"\bmessages\x18\x01 \x03(\v2\x1a.moderation.v1.ChatMessageR\bmessages\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"k\n" +
	"\vChatSummary\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12=\n" +
	"\flast_message\x18\x02 \x01(\v2\x1a.moderation.v1.ChatMessageR\vlastMessage\"F\n" +
	"\x16ListActiveChatsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"a\n" +
	"\x17ListActiveChatsResponse\x120\n" +
	"\x05chats\x18\x01 \x03(\v2\x1a.moderation.v1.ChatSummaryR\x05chats\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total*\xc1\x01\n" +
	"\rRequestStatus\x12\x1e\n" +
	"\x1aREQUEST_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16REQUEST_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18REQUEST_STATUS_IN_REVIEW\x10\x02\x12\x1b\n" +
	"\x17REQUEST_STATUS_APPROVED\x10\x03\x12\x1b\n" +
	"\x17REQUEST_STATUS_REJECTED\x10\x04\x12\x1c\n" +
	"\x18REQUEST_STATUS_CANCELLED\x10\x05*w\n" +
	"\n" +
	"SenderRole\x12\x1b\n" +
	"\x17SENDER_ROLE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SENDER_ROLE_DEVELOPER\x10\x01\x12\x19\n" +
	"\x15SENDER_ROLE_MODERATOR\x10\x02\x12\x16\n" +
	"\x12SENDER_ROLE_SYSTEM\x10\x03*\xb5\x01\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_TYPE_TEXT\x10\x01\x12\x1a\n" +
	"\x16MESSAGE_TYPE_SUBMITTED\x10\x02\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_STATUS_CHANGED\x10\x03\x12\x19\n" +
	"\x15MESSAGE_TYPE_APPROVED\x10\x04\x12\x19\n" +
	"\x15MESSAGE_TYPE_REJECTED\x10\x052\xe7\v\n" +
	"\x11ModerationService\x12T\n" +
	"\vSubmitDraft\x12!.moderation.v1.SubmitDraftRequest\x1a\".moderation.v1.SubmitDraftResponse\x12\x90\x01\n" +
	"\fListRequests\x12,.moderation.v1.ListModerationRequestsRequest\x1a-.moderation.v1.ListModerationRequestsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/moderation/requests\x12\x97\x01\n" +
	"\n" +
	"GetRequest\x12*.moderation.v1.GetModerationRequestRequest\x1a+.moderation.v1.GetModerationRequestResponse\"0\x82\xd3\xe4\x93\x02*\x12(/api/v1/moderation/requests/{request_id}\x12\xb2\x01\n" +
	"\x19GetLatestRequestByProject\x12/.moderation.v1.GetLatestRequestByProjectRequest\x1a+.moderation.v1.GetModerationRequestResponse\"7\x82\xd3\xe4\x93\x021\x12//api/v1/moderation/projects/{project_id}/latest\x12\xa6\x01\n" +
	"\fClaimRequest\x12,.moderation.v1.ClaimModerationRequestRequest\x1a-.moderation.v1.ClaimModerationRequestResponse\"9\x82\xd3\xe4\x93\x023:\x01*\"./api/v1/moderation/requests/{request_id}/claim\x12\x99\x01\n" +
	"\aApprove\x12'.moderation.v1.ApproveModerationRequest\x1a(.moderation.v1.ApproveModerationResponse\";\x82\xd3\xe4\x93\x025:\x01*\"0/api/v1/moderation/projects/{project_id}/approve\x12\x95\x01\n" +
	"\x06Reject\x12&.moderation.v1.RejectModerationRequest\x1a'.moderation.v1.RejectModerationResponse\":\x82\xd3\xe4\x93\x024:\x01*\"//api/v1/moderation/projects/{project_id}/reject\x12\x9a\x01\n" +
	"\vSendMessage\x12%.moderation.v1.SendChatMessageRequest\x1a&.moderation.v1.SendChatMessageResponse\"<\x82\xd3\xe4\x93\x026:\x01*\"1/api/v1/moderation/projects/{project_id}/messages\x12\x9a\x01\n" +
	"\fListMessages\x12&.moderation.v1.ListChatMessagesRequest\x1a'.moderation.v1.ListChatMessagesResponse\"9\x82\xd3\xe4\x93\x023\x121/api/v1/moderation/projects/{project_id}/messages\x12\x82\x01\n" +
	"\x0fListActiveChats\x12%.moderation.v1.ListActiveChatsRequest\x1a&.moderation.v1.ListActiveChatsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/moderation/chatsB\xc1\x01\n" +
	"\x11com.moderation.v1B\x0fModerationProtoP\x01ZFgithub.com/Be4Die/game-developer-hub/protos/moderation/v1;moderationv1\xa2\x02\x03MXX\xaa\x02\rModeration.V1\xca\x02\rModeration\\V1\xe2\x02\x19Moderation\\V1\\GPBMetadata\xea\x02\x0eModeration::V1b\x06proto3"

var (
	file_moderation_v1_moderation_proto_rawDescOnce sync.Once
	file_moderation_v1_moderation_proto_rawDescData []byte
)

func file_moderation_v1_moderation_proto_rawDescGZIP() []byte {
	file_moderation_v1_moderation_proto_rawDescOnce.Do(func() {
		file_moderation_v1_moderation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moderation_v1_moderation_proto_rawDesc), len(file_moderation_v1_moderation_proto_rawDesc)))
	})
	return file_moderation_v1_moderation_proto_rawDescData
}

var file_moderation_v1_moderation_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_moderation_v1_moderation_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_moderation_v1_moderation_proto_goTypes = []any{
	(RequestStatus)(0),                       // 0: moderation.v1.RequestStatus
	(SenderRole)(0),                          // 1: moderation.v1.SenderRole
	(MessageType)(0),                         // 2: moderation.v1.MessageType
	(*ProjectSnapshot)(nil),                  // 3: moderation.v1.ProjectSnapshot
	(*ModerationRequest)(nil),                // 4: moderation.v1.ModerationRequest
	(*ChatMessage)(nil),                      // 5: moderation.v1.ChatMessage
	(*SubmitDraftRequest)(nil),               // 6: moderation.v1.SubmitDraftRequest
	(*SubmitDraftResponse)(nil),              // 7: moderation.v1.SubmitDraftResponse
	(*ListModerationRequestsRequest)(nil),    // 8: moderation.v1.ListModerationRequestsRequest
	(*ListModerationRequestsResponse)(nil),   // 9: moderation.v1.ListModerationRequestsResponse
	(*GetModerationRequestRequest)(nil),      // 10: moderation.v1.GetModerationRequestRequest
	(*GetModerationRequestResponse)(nil),     // 11: moderation.v1.GetModerationRequestResponse
	(*GetLatestRequestByProjectRequest)(nil), // 12: moderation.v1.GetLatestRequestByProjectRequest
	(*ClaimModerationRequestRequest)(nil),    // 13: moderation.v1.ClaimModerationRequestRequest
	(*ClaimModerationRequestResponse)(nil),   // 14: moderation.v1.ClaimModerationRequestResponse
	(*ApproveModerationRequest)(nil),         // 15: moderation.v1.ApproveModerationRequest
	(*ApproveModerationResponse)(nil),        // 16: moderation.v1.ApproveModerationResponse
	(*RejectModerationRequest)(nil),          // 17: moderation.v1.RejectModerationRequest
	(*RejectModerationResponse)(nil),         // 18: moderation.v1.RejectModerationResponse
	(*SendChatMessageRequest)(nil),           // 19: moderation.v1.SendChatMessageRequest
	(*SendChatMessageResponse)(nil),          // 20: moderation.v1.SendChatMessageResponse
	(*ListChatMessagesRequest)(nil),          // 21: moderation.v1.ListChatMessagesRequest
	(*ListChatMessagesResponse)(nil),         // 22: moderation.v1.ListChatMessagesResponse
	(*ChatSummary)(nil),                      // 23: moderation.v1.ChatSummary
	(*ListActiveChatsRequest)(nil),           // 24: moderation.v1.ListActiveChatsRequest
	(*ListActiveChatsResponse)(nil),          // 25: moderation.v1.ListActiveChatsResponse
}
var file_moderation_v1_moderation_proto_depIdxs = []int32{
	0,  // 0: moderation.v1.ModerationRequest.status:type_name -> moderation.v1.RequestStatus
	3,  // 1: moderation.v1.ModerationRequest.snapshot:type_name -> moderation.v1.ProjectSnapshot
	1,  // 2: moderation.v1.ChatMessage.sender_role:type_name -> moderation.v1.SenderRole
	2,  // 3: moderation.v1.ChatMessage.message_type:type_name -> moderation.v1.MessageType
	3,  // 4: moderation.v1.SubmitDraftRequest.snapshot:type_name -> moderation.v1.ProjectSnapshot
	4,  // 5: moderation.v1.SubmitDraftResponse.request:type_name -> moderation.v1.ModerationRequest
	0,  // 6: moderation.v1.ListModerationRequestsRequest.status:type_name -> moderation.v1.RequestStatus
	4,  // 7: moderation.v1.ListModerationRequestsResponse.requests:type_name -> moderation.v1.ModerationRequest
	4,  // 8: moderation.v1.GetModerationRequestResponse.request:type_name -> moderation.v1.ModerationRequest
	4,  // 9: moderation.v1.ClaimModerationRequestResponse.request:type_name -> moderation.v1.ModerationRequest
	4,  // 10: moderation.v1.ApproveModerationResponse.request:type_name -> moderation.v1.ModerationRequest
	4,  // 11: moderation.v1.RejectModerationResponse.request:type_name -> moderation.v1.ModerationRequest
	5,  // 12: moderation.v1.SendChatMessageResponse.message:type_name -> moderation.v1.ChatMessage
	5,  // 13: moderation.v1.ListChatMessagesResponse.messages:type_name -> moderation.v1.ChatMessage
	5,  // 14: moderation.v1.ChatSummary.last_message:type_name -> moderation.v1.ChatMessage
	23, // 15: moderation.v1.ListActiveChatsResponse.chats:type_name -> moderation.v1.ChatSummary
	6,  // 16: moderation.v1.ModerationService.SubmitDraft:input_type -> moderation.v1.SubmitDraftRequest
	8,  // 17: moderation.v1.ModerationService.ListRequests:input_type -> moderation.v1.ListModerationRequestsRequest
	10, // 18: moderation.v1.ModerationService.GetRequest:input_type -> moderation.v1.GetModerationRequestRequest
	12, // 19: moderation.v1.ModerationService.GetLatestRequestByProject:input_type -> moderation.v1.GetLatestRequestByProjectRequest
	13, // 20: moderation.v1.ModerationService.ClaimRequest:input_type -> moderation.v1.ClaimModerationRequestRequest
	15, // 21: moderation.v1.ModerationService.Approve:input_type -> moderation.v1.ApproveModerationRequest
	17, // 22: moderation.v1.ModerationService.Reject:input_type -> moderation.v1.RejectModerationRequest
	19, // 23: moderation.v1.ModerationService.SendMessage:input_type -> moderation.v1.SendChatMessageRequest
	21, // 24: moderation.v1.ModerationService.ListMessages:input_type -> moderation.v1.ListChatMessagesRequest
	24, // 25: moderation.v1.ModerationService.ListActiveChats:input_type -> moderation.v1.ListActiveChatsRequest
	7,  // 26: moderation.v1.ModerationService.SubmitDraft:output_type -> moderation.v1.SubmitDraftResponse
	9,  // 27: moderation.v1.ModerationService.ListRequests:output_type -> moderation.v1.ListModerationRequestsResponse
	11, // 28: moderation.v1.ModerationService.GetRequest:output_type -> moderation.v1.GetModerationRequestResponse
	11, // 29: moderation.v1.ModerationService.GetLatestRequestByProject:output_type -> moderation.v1.GetModerationRequestResponse
	14, // 30: moderation.v1.ModerationService.ClaimRequest:output_type -> moderation.v1.ClaimModerationRequestResponse
	16, // 31: moderation.v1.ModerationService.Approve:output_type -> moderation.v1.ApproveModerationResponse
	18, // 32: moderation.v1.ModerationService.Reject:output_type -> moderation.v1.RejectModerationResponse
	20, // 33: moderation.v1.ModerationService.SendMessage:output_type -> moderation.v1.SendChatMessageResponse
	22, // 34: moderation.v1.ModerationService.ListMessages:output_type -> moderation.v1.ListChatMessagesResponse
	25, // 35: moderation.v1.ModerationService.ListActiveChats:output_type -> moderation.v1.ListActiveChatsResponse
	26, // [26:36] is the sub-list for method output_type
	16, // [16:26] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_moderation_v1_moderation_proto_init() }
func file_moderation_v1_moderation_proto_init() {
	if File_moderation_v1_moderation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moderation_v1_moderation_proto_rawDesc), len(file_moderation_v1_moderation_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moderation_v1_moderation_proto_goTypes,
		DependencyIndexes: file_moderation_v1_moderation_proto_depIdxs,
		EnumInfos:         file_moderation_v1_moderation_proto_enumTypes,
		MessageInfos:      file_moderation_v1_moderation_proto_msgTypes,
	}.Build()
	File_moderation_v1_moderation_proto = out.File
	file_moderation_v1_moderation_proto_goTypes = nil
	file_moderation_v1_moderation_proto_depIdxs = nil
}
