graph TD
    %% Определение строгого стиля для печати
    classDef printStyle fill:#fff,stroke:#000,stroke-width:2px,color:#000;

    %% Переопределение цвета стрелок на черный
    linkStyle default stroke:#000,stroke-width:2px;

    %% Узлы диаграммы
    A[Основатель ИП Теплов С.Д.] --> B[Соучредитель / Ведущий менеджер]
    B --> C[Технический отдел]
    B --> D[Отдел модерации]
    B --> E[Студия внутренней разработки игр]
    C --> C1[Разработчик серверной части]
    C --> C2[Разработчик клиентской части]
    C --> C3[Инженер по эксплуатации]
    D --> D1[Специалист по модерации]
    E --> E1[Unity разработчик]
    E --> E2[Художники]

    %% Применение стиля ко всем узлам
    class A,B,C,D,E,C1,C2,C3,D1,E1,E2 printStyle;
