env: "local"
grpc:
  port: 44044
  timeout: 10h
node:
  region: "local"
  version: "0.0.1"
  # eth_name: "eth0"  # Опционально: имя сетевого интерфейса для автоопределения адреса
  data_dir: "/app/data"
orchestrator:
  mode: "auto-discovery"
  address: "orchestrator:50052"
  announce_interval: 30s
  announce_timeout: 10s
  # Используем адрес шлюза Docker bridge для подключения клиентов извне Docker (Linux)
  external_address: "172.17.0.1:44044"
